'use client';
import {useRef,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
import {aboutSectionNames,type AboutContent} from '@/lib/about-content';
import {Plus,ArrowUp,ArrowDown,ImagePlus,ExternalLink,UserRound} from 'lucide-react';
function Field({label,children}:{label:string,children:ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>;}
export default function AboutEditor({value,change,upload,setUploading,setError}:{value:AboutContent;change:(fn:(a:AboutContent)=>AboutContent)=>void;upload:(f:File)=>Promise<string>;setUploading:(v:boolean)=>void;setError:(s:string)=>void}){
 const [area,setArea]=useState<keyof typeof aboutSectionNames>('hero');
 const input=useRef<HTMLInputElement>(null);const target=useRef('');
 function teamEdit(id:string,p:Partial<AboutContent['team'][number]>){change(a=>({...a,team:a.team.map(m=>m.id===id?{...m,...p}:m)}));}
 async function photo(file:File|undefined){if(!file)return;const id=target.current;setUploading(true);setError('');try{const url=await upload(file);if(id==='intro')change(a=>({...a,intro:{...a.intro,image:url}}));else teamEdit(id,{image:url});}catch(e){setError(e instanceof Error?e.message:'Unable to upload photo.');}finally{setUploading(false);if(input.current)input.current.value='';}}
 const block=area==='intro'||area==='vision'||area==='mission'?value[area]:null;
 return <><div className="panel-heading"><div><h2>About SOMDAS</h2><p>Manage each section, edit your story and introduce your team.</p></div><Button variant="outline" asChild><a href="/about" target="_blank" rel="noreferrer">View saved About page <ExternalLink/></a></Button></div>
 <div className="section-controls about-section-controls">{Object.entries(aboutSectionNames).map(([id,label])=><div className="section-control" key={id}><button type="button" className="about-section-choice" aria-pressed={area===id} onClick={()=>setArea(id as typeof area)}><strong>{label}</strong><small>{value.sections[id as typeof area]?'Enabled':'Hidden'}{id==='team'&&!value.team.some(m=>m.visible)?' · No visible profiles':''}</small></button><Switch aria-label={`Show About section: ${label}`} checked={value.sections[id as typeof area]} onCheckedChange={on=>change(a=>({...a,sections:{...a.sections,[id]:on}}))}/></div>)}</div>
 <div className="cms-panel about-edit-panel"><h3>{aboutSectionNames[area]}</h3><p className="form-hint">Select a section above to edit it. Hidden sections leave no empty space.</p>
 {(area==='hero'||area==='join')&&<><Field label="Eyebrow"><Input value={value[area].eyebrow} maxLength={80} onChange={e=>change(a=>({...a,[area]:{...a[area],eyebrow:e.target.value}}))}/></Field><Field label="Heading"><Textarea rows={2} value={value[area].title} maxLength={180} onChange={e=>change(a=>({...a,[area]:{...a[area],title:e.target.value}}))}/></Field><Field label="Introduction"><Textarea value={value[area].body} maxLength={700} onChange={e=>change(a=>({...a,[area]:{...a[area],body:e.target.value}}))}/></Field></>}
 {block&&(area==='intro'||area==='vision'||area==='mission')&&<><Field label="Eyebrow"><Input value={block.eyebrow} maxLength={80} onChange={e=>change(a=>({...a,[area]:{...a[area],eyebrow:e.target.value}}))}/></Field><Field label="Heading"><Textarea rows={2} value={block.title} maxLength={180} onChange={e=>change(a=>({...a,[area]:{...a[area],title:e.target.value}}))}/></Field><Field label="Lead paragraph"><Textarea rows={3} value={block.lead} maxLength={700} onChange={e=>change(a=>({...a,[area]:{...a[area],lead:e.target.value}}))}/></Field><Field label="Full text (separate paragraphs with a blank line)"><Textarea rows={7} value={block.body} maxLength={6000} onChange={e=>change(a=>({...a,[area]:{...a[area],body:e.target.value}}))}/></Field>{area==='intro'&&<div className="about-banner-editor">{value.intro.image&&<img src={value.intro.image} alt="Current Who we are banner"/>}<div><Button variant="outline" onClick={()=>{target.current='intro';input.current?.click();}}><ImagePlus/>Replace banner image</Button><Field label="Image caption"><Input value={value.intro.caption} maxLength={250} onChange={e=>change(a=>({...a,intro:{...a.intro,caption:e.target.value}}))}/></Field></div></div>}</>}
 {area==='difference'&&<><Field label="Eyebrow"><Input value={value.difference.eyebrow} maxLength={80} onChange={e=>change(a=>({...a,difference:{...a.difference,eyebrow:e.target.value}}))}/></Field><Field label="Heading"><Input value={value.difference.title} maxLength={180} onChange={e=>change(a=>({...a,difference:{...a.difference,title:e.target.value}}))}/></Field><Field label="Introduction"><Textarea value={value.difference.body} maxLength={700} onChange={e=>change(a=>({...a,difference:{...a.difference,body:e.target.value}}))}/></Field>{value.difference.items.map((item,i)=><div className="cms-panel" key={i}><Field label={`Card ${i+1} heading`}><Input value={item.title} maxLength={120} onChange={e=>change(a=>({...a,difference:{...a.difference,items:a.difference.items.map((x,j)=>i===j?{...x,title:e.target.value}:x)}}))}/></Field><Field label="Card description"><Textarea value={item.body} maxLength={800} onChange={e=>change(a=>({...a,difference:{...a.difference,items:a.difference.items.map((x,j)=>i===j?{...x,body:e.target.value}:x)}}))}/></Field></div>)}</>}
 {area==='team'&&<><div className="two-fields"><Field label="Section heading"><Input value={value.teamTitle} maxLength={180} onChange={e=>change(a=>({...a,teamTitle:e.target.value}))}/></Field><Field label="Section introduction"><Input value={value.teamIntro} maxLength={700} onChange={e=>change(a=>({...a,teamIntro:e.target.value}))}/></Field></div><div className="panel-heading"><p>Two profiles per row on desktop. Add real profiles here; none are published by default.</p><Button onClick={()=>change(a=>({...a,team:[...a.team,{id:crypto.randomUUID(),name:'New team member',role:'',bio:'',image:'',imageAlt:'',linkedin:'',visible:false}]}))}><Plus/>Add team member</Button></div>{!value.team.length&&<div className="cms-empty"><UserRound/><h3>Introduce your team</h3><p>Add a photo, name, role and biography. Switch the profile on when it is ready. The team section stays hidden while there are no visible profiles.</p></div>}
 {value.team.map((m,i)=><div className="cms-panel team-editor-card" key={m.id}><div className="team-editor-profile"><button className="logo-upload" aria-label={`Upload photo for ${m.name}`} onClick={()=>{target.current=m.id;input.current?.click();}}>{m.image?<img src={m.image} alt={m.imageAlt||m.name}/>:<><ImagePlus/><span>Upload profile photo</span></>}</button><small>JPEG, PNG or WebP<br/>Up to 8 MB</small>{m.image&&<Button variant="ghost" size="sm" onClick={()=>teamEdit(m.id,{image:'',imageAlt:''})}>Remove photo</Button>}</div><div className="team-editor-fields"><div className="two-fields"><Field label="Full name"><Input value={m.name} maxLength={120} onChange={e=>teamEdit(m.id,{name:e.target.value})}/></Field><Field label="Role / title"><Input placeholder="e.g. Co-founder & Executive Director" value={m.role} maxLength={150} onChange={e=>teamEdit(m.id,{role:e.target.value})}/></Field></div><Field label="Biography / responsibilities"><Textarea rows={4} value={m.bio} maxLength={3000} onChange={e=>teamEdit(m.id,{bio:e.target.value})}/></Field><div className="two-fields"><Field label="Photo description (optional)"><Input value={m.imageAlt} maxLength={250} placeholder={m.name} onChange={e=>teamEdit(m.id,{imageAlt:e.target.value})}/></Field><Field label="LinkedIn URL (optional)"><Input value={m.linkedin} type="url" placeholder="https://www.linkedin.com/in/…" onChange={e=>teamEdit(m.id,{linkedin:e.target.value})}/></Field></div><div className="team-editor-actions"><label className="team-visible"><Switch aria-label={`Show profile for ${m.name}`} checked={m.visible} onCheckedChange={on=>teamEdit(m.id,{visible:on})}/>Show profile</label><Button variant="outline" size="icon" disabled={!i} aria-label={`Move ${m.name} up`} onClick={()=>change(a=>{const team=[...a.team];[team[i-1],team[i]]=[team[i],team[i-1]];return {...a,team};})}><ArrowUp/></Button><Button variant="outline" size="icon" disabled={i===value.team.length-1} aria-label={`Move ${m.name} down`} onClick={()=>change(a=>{const team=[...a.team];[team[i+1],team[i]]=[team[i],team[i+1]];return {...a,team};})}><ArrowDown/></Button><Button variant="ghost" onClick={()=>{if(confirm(`Remove ${m.name}? Save changes to apply.`))change(a=>({...a,team:a.team.filter(x=>x.id!==m.id)}));}}>Remove profile</Button></div></div></div>)}
 </>}
 <input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>photo(e.target.files?.[0])}/>
 </div></>;
}
