'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
type Message={id:string;name:string;email:string;topic:string;message:string;created_at:string};
export default function Messages({endpoint='/api/editor/messages'}:{endpoint?:string}){const [items,setItems]=useState<Message[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function load(p:number){setBusy(true);setError('');try{const r=await fetch(endpoint+'?page='+p,{cache:'no-store'});const d=await r.json() as {error?:string;messages:Message[];more:boolean};if(!r.ok)throw Error(d.error||'Could not load messages.');setItems(d.messages);setMore(d.more);setPage(p);}catch(e){setError(e instanceof Error?e.message:'Could not load messages.');}finally{setBusy(false);}}
 useEffect(()=>{queueMicrotask(()=>{void load(0);});},[]);
 return <><div className="panel-heading"><div><h2>Contact messages</h2><p>Private enquiries received through your contact page. Messages are saved here; email notifications are not enabled.</p></div><Button variant="outline" disabled={busy} onClick={()=>load(page)}>Refresh</Button></div>{error&&<p role="alert" className="cms-error">{error}</p>}{busy?<p role="status">Loading messages…</p>:items.length?items.map(m=><article className="cms-panel" key={m.id}><div className="panel-heading"><div><span className="cms-pill">{m.topic}</span><h3>{m.name}</h3><a href={'mailto:'+m.email}>{m.email}</a></div><time dateTime={m.created_at}>{new Date(m.created_at).toLocaleString()}</time></div><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{m.message}</p><Button variant="outline" asChild><a href={'mailto:'+m.email+'?subject='+encodeURIComponent('Re: '+m.topic)}>Reply by email</a></Button></article>):!error&&<div className="cms-empty"><h3>No messages yet</h3><p>New enquiries from the contact page will appear here.</p></div>}<div style={{display:'flex',gap:16,alignItems:'center'}}><Button variant="outline" disabled={busy||page===0} onClick={()=>load(page-1)}>Previous</Button><span>Page {page+1}</span><Button variant="outline" disabled={busy||!more} onClick={()=>load(page+1)}>Next</Button></div></>;
}
