'use client';
import {useState,type ReactNode} from 'react';
import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';import {Switch} from '@/components/ui/switch';import {Button} from '@/components/ui/button';
import {sodiSections,type SodiContent} from '@/lib/sodi-content';
function Field({label,children}:{label:string,children:ReactNode}){return <label className="editor-field"><span>{label}</span>{children}</label>;}
export default function SodiEditor({value,change}:{value:SodiContent;change:(fn:(s:SodiContent)=>SodiContent)=>void}){
 const [section,setSection]=useState<keyof typeof sodiSections>('hero');
 return <><div className="panel-heading"><div><h2>SODI introduction page</h2><p>Manage content, section visibility and links to the main platform.</p></div><Button variant="outline" asChild><a href="/programs/sodi" target="_blank" rel="noreferrer">View saved SODI page ↗</a></Button></div><div className="cms-panel"><div className="inline-switch"><div><strong>Main SODI platform is available</strong><p>Enable only when its website and downloads are ready. Until then, categories are labelled Planned.</p></div><Switch checked={value.platformReady} aria-label="Main SODI platform is available" onCheckedChange={on=>change(s=>({...s,platformReady:on}))}/></div><Field label="Live platform URL"><Input type="url" placeholder="https://sodi.somdas.org" value={value.platformUrl} onChange={e=>change(s=>({...s,platformUrl:e.target.value}))}/></Field></div>
 <div className="section-controls about-section-controls">{Object.entries(sodiSections).map(([id,label])=><div className="section-control" key={id}><button className="about-section-choice" aria-pressed={section===id} onClick={()=>setSection(id as typeof section)}><strong>{label}</strong><small>{value.sections[id as typeof section]?'Enabled':'Hidden'}</small></button><Switch checked={value.sections[id as typeof section]} aria-label={`Show ${label}`} onCheckedChange={on=>change(s=>({...s,sections:{...s.sections,[id]:on}}))}/></div>)}</div>
 <div className="cms-panel about-edit-panel"><h3>{sodiSections[section]}</h3>{section==='categories'?<><Field label="Section heading"><Textarea value={value.categoriesTitle} maxLength={180} onChange={e=>change(s=>({...s,categoriesTitle:e.target.value}))}/></Field><Field label="Section introduction"><Textarea value={value.categoriesIntro} maxLength={700} onChange={e=>change(s=>({...s,categoriesIntro:e.target.value}))}/></Field>{value.categories.map((cat,i)=><div className="cms-panel" key={cat.id}><div className="inline-switch"><strong>Category {i+1}</strong><Switch checked={cat.visible} aria-label={`Show category ${cat.title}`} onCheckedChange={on=>change(s=>({...s,categories:s.categories.map(x=>x.id===cat.id?{...x,visible:on}:x)}))}/></div><Field label="Category name"><Input value={cat.title} maxLength={100} onChange={e=>change(s=>({...s,categories:s.categories.map(x=>x.id===cat.id?{...x,title:e.target.value}:x)}))}/></Field><Field label="Description"><Textarea value={cat.body} maxLength={500} onChange={e=>change(s=>({...s,categories:s.categories.map(x=>x.id===cat.id?{...x,body:e.target.value}:x)}))}/></Field><Field label="Category URL on the SODI platform"><Input type="url" value={cat.url} placeholder="https://…" onChange={e=>change(s=>({...s,categories:s.categories.map(x=>x.id===cat.id?{...x,url:e.target.value}:x)}))}/></Field><div className="item-actions"><Button variant="outline" disabled={i===0} onClick={()=>change(s=>{const categories=[...s.categories];[categories[i-1],categories[i]]=[categories[i],categories[i-1]];return {...s,categories};})}>Move up</Button><Button variant="outline" disabled={i===value.categories.length-1} onClick={()=>change(s=>{const categories=[...s.categories];[categories[i+1],categories[i]]=[categories[i],categories[i+1]];return {...s,categories};})}>Move down</Button><Button variant="ghost" onClick={()=>change(s=>({...s,categories:s.categories.filter(x=>x.id!==cat.id)}))}>Remove</Button></div></div>)}<Button onClick={()=>change(s=>({...s,categories:[...s.categories,{id:crypto.randomUUID(),title:'New category',body:'',url:'',visible:false}]}))}>Add category</Button></>:<><Field label="Heading"><Textarea rows={3} value={value[section].title} maxLength={180} onChange={e=>change(s=>({...s,[section]:{...s[section],title:e.target.value}}))}/></Field><Field label="Text (separate paragraphs with a blank line)"><Textarea rows={7} value={value[section].body} maxLength={6000} onChange={e=>change(s=>({...s,[section]:{...s[section],body:e.target.value}}))}/></Field>{section==='programs'&&<p>Program numbers stay fixed: SODI 01, AI & Research 02, Academy 03, SOMDAS Lab 04, SOMDAS Solutions 05. Links open their SOMDAS introduction pages.</p>}{section==='hero'&&<p>The catalog image is the supplied design reference and is labelled as a platform preview.</p>}</>}</div></>;
}
