'use client';
import {useEffect,useState} from 'react';
type Report={days:number;summary:{views:number;visitors:number};prior:{views:number;visitors:number};trend:{date:string;views:number;visitors:number}[];pages:{path:string;views:number;visitors:number}[];referrers:{referrer:string;views:number}[];devices:{device:string;views:number}[]};
export default function AnalyticsView(){
 const [days,setDays]=useState(30),[data,setData]=useState<Report|null>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/admin/analytics?days='+days,{cache:'no-store'}).then(async response=>{const result=await response.json() as Report&{error?:string};if(!response.ok)throw Error(result.error);setError('');setData(result);}).catch(error=>setError(error instanceof Error?error.message:'Unable to load analytics.'));},[days]);
 const max=Math.max(1,...(data?.trend.map(item=>item.views)??[])),change=(current:number,previous:number)=>previous?Math.round((current-previous)/previous*100):current?100:0;
 return <>{error&&<p className="cms-error">{error}</p>}<div className="cms-toolbar"><p>Anonymous page views only. IP addresses and personal details are not stored.</p><select value={days} onChange={event=>setDays(Number(event.target.value))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div>{data&&<><div className="analytics-summary"><div><span>Page views</span><strong>{data.summary.views.toLocaleString()}</strong><small>{change(data.summary.views,data.prior.views)}% vs previous period</small></div><div><span>Unique visitors</span><strong>{data.summary.visitors.toLocaleString()}</strong><small>{change(data.summary.visitors,data.prior.visitors)}% vs previous period</small></div></div><section className="analytics-section"><h2>Traffic over time</h2><div className="analytics-bars" aria-label="Daily page views">{data.trend.map(item=><div key={item.date} title={`${item.date}: ${item.views} views, ${item.visitors} visitors`}><span style={{height:`${Math.max(3,item.views/max*100)}%`}}/><small>{new Date(item.date+'T00:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></div>)}</div>{!data.trend.length&&<p className="cms-empty">Analytics collection has started. Visits will appear here.</p>}</section><div className="analytics-grid"><section><h2>Top pages</h2><table><thead><tr><th>Page</th><th>Views</th><th>Visitors</th></tr></thead><tbody>{data.pages.map(item=><tr key={item.path}><td>{item.path}</td><td>{item.views}</td><td>{item.visitors}</td></tr>)}</tbody></table></section><section><h2>Traffic sources</h2><table><thead><tr><th>Source</th><th>Views</th></tr></thead><tbody>{data.referrers.map(item=><tr key={item.referrer}><td>{item.referrer}</td><td>{item.views}</td></tr>)}</tbody></table><h2>Devices</h2><table><tbody>{data.devices.map(item=><tr key={item.device}><td>{item.device}</td><td>{item.views}</td></tr>)}</tbody></table></section></div></>}</>;
}
