'use client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Switch} from '@/components/ui/switch';
import {initialContent,sectionNames,type Content,type PostType} from '@/lib/content';
import {human} from '@/lib/section-catalog';
import homeLabels from '@/lib/home-labels.json';
function blank(sample:any):any {if(Array.isArray(sample))return [];if(sample&&typeof sample==='object')return Object.fromEntries(Object.entries(sample).map(([k,v])=>[k,k==='id'?crypto.randomUUID():k==='status'?v:blank(v)]));return typeof sample==='boolean'?false:typeof sample==='number'?0:'';}
function newItem(path:string,sample:any){if(sample!==undefined)return blank(sample);const id=crypto.randomUUID();if(path.endsWith('team'))return {id,name:'New member',role:'',bio:'',image:'',imageAlt:'',linkedin:'',visible:false};if(path.endsWith('projects'))return {id,title:'New research',summary:'',category:'',status:'ongoing',date:'',author:'',url:'',image:'',imageAlt:'',visible:false};if(path.endsWith('offerings'))return {id,title:'New course',summary:'',level:'',format:'',date:'',url:'',status:'planned',visible:false};if(path.endsWith('entries'))return {id,title:'New project',summary:'',status:'concept',url:'',visible:false};if(path.endsWith('images'))return {url:'',alt:''};return '';}
const postTypeLabels:Record<PostType,string>={event:'Event',announcement:'Announcement',opportunity:'Opportunity',story:'Story / Publication'};
const postLabels:Record<string,string>={title:'Title',summary:'Short summary',body:'Full content',category:'Category',author:'Author',publishDate:'Publish date',date:'Start date',endDate:'End date',time:'Time',location:'Location',eventFormat:'Event format',registrationUrl:'Registration link',organizer:'Organizer',capacity:'Capacity',announcementDate:'Announcement date',priority:'Priority',expiryDate:'Expiry date',attachmentUrl:'Attachment link',deadline:'Application deadline',eligibility:'Eligibility',opportunityType:'Opportunity type',applicationUrl:'Application link',organization:'Organization',contributors:'Authors / contributors',publicationDate:'Publication date',documentUrl:'Document / PDF link',externalUrl:'External link',readingTime:'Reading time',images:'Images',cover:'Cover image number'};
const dateKeys=new Set(['publishDate','date','endDate','announcementDate','expiryDate','deadline','publicationDate']);
const urlKeys=new Set(['registrationUrl','attachmentUrl','applicationUrl','documentUrl','externalUrl']);
function PostFields({post,path,onChange,content,onUploading}:{post:any,path:string,onChange:(v:any)=>void,content:Content,onUploading?:(v:boolean)=>void}){
 const type=(post.postType||'event') as PostType,update=(key:string,value:any)=>onChange({...post,[key]:value});
 const control=(key:string)=>{const value=post[key]??'',label=postLabels[key]??human(key);if(key==='category')return <label className="cms-field" key={key}>{label}<select value={value} onChange={e=>update(key,e.target.value)}>{content.categories.map(o=><option key={o}>{o}</option>)}</select></label>;if(key==='priority')return <label className="cms-field" key={key}>{label}<select value={value} onChange={e=>update(key,e.target.value)}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></label>;const multiline=['summary','body','eligibility','contributors'].includes(key);return <label className="cms-field" key={key}>{label}{multiline?<Textarea rows={key==='body'?12:key==='summary'?4:6} value={value} onChange={e=>update(key,e.target.value)}/>:<Input type={dateKeys.has(key)?'date':urlKeys.has(key)?'url':'text'} value={value} placeholder={urlKeys.has(key)?'https://…':undefined} onChange={e=>update(key,e.target.value)}/>}</label>;};
 const specifics:Record<PostType,string[]>={event:['date','endDate','time','location','eventFormat','registrationUrl','organizer','capacity'],announcement:['announcementDate','priority','expiryDate','attachmentUrl'],opportunity:['deadline','eligibility','opportunityType','applicationUrl','organization','location'],story:['contributors','publicationDate','documentUrl','externalUrl','readingTime']};
 return <div className="cms-post-editor"><div className="cms-post-type-summary"><span>{postTypeLabels[type]}</span><p>Post type is fixed after creation so its content and validation stay consistent.</p></div><fieldset><legend>Post content</legend>{['title','summary','body','category','author','publishDate'].map(control)}</fieldset><fieldset><legend>{postTypeLabels[type]} details</legend>{specifics[type].map(control)}</fieldset><fieldset><legend>Media</legend><Fields value={post.images??[]} path={path+'.images'} onChange={v=>update('images',v)} content={content} onUploading={onUploading}/>{(post.images?.length??0)>1&&<label className="cms-field">Cover image number<Input type="number" min={0} max={post.images.length-1} value={post.cover??0} onChange={e=>update('cover',Number(e.target.value))}/><small>First image is 0, second image is 1.</small></label>}</fieldset></div>;
}
export default function Fields({value,path,onChange,content,onUploading,canToggleVisibility=true}:{value:any,path:string,onChange:(v:any)=>void,content:Content,onUploading?:(v:boolean)=>void,canToggleVisibility?:boolean}){
 const key=path.split('.').at(-1)!,label=(path.startsWith('home.')?(homeLabels as Record<string,Record<string,string>>)[path.split('.')[1]]?.[key]:null)??human(key);
 if(path.startsWith('@')&&value&&typeof value==='object'&&!Array.isArray(value))return <PostFields post={value} path={path} onChange={onChange} content={content} onUploading={onUploading}/>;
 if(key==='status'&&path.startsWith('@'))return null;
 if(Array.isArray(value)){
  if(key==='sectionOrder')return <fieldset><legend>Homepage section order</legend><p className="cms-help">Move sections into the order visitors should see them.</p>{value.map((id:string,i:number)=><div className="cms-list-item" key={id}><div className="cms-item-heading"><strong>{sectionNames[id as keyof typeof sectionNames]??human(id)}</strong><div><Button variant="ghost" disabled={!i} onClick={()=>{const a=[...value];[a[i-1],a[i]]=[a[i],a[i-1]];onChange(a);}}>Move up</Button><Button variant="ghost" disabled={i===value.length-1} onClick={()=>{const a=[...value];[a[i+1],a[i]]=[a[i],a[i+1]];onChange(a);}}>Move down</Button></div></div></div>)}</fieldset>;
  if(key==='featured')return <fieldset><legend>Homepage featured posts · up to three</legend>{content.events.filter(e=>e.status==='published').map(e=><label className="cms-check" key={e.id}><input type="checkbox" checked={value.includes(e.id)} disabled={!value.includes(e.id)&&value.length>=3} onChange={x=>onChange(x.target.checked?[...value,e.id]:value.filter((id:string)=>id!==e.id))}/>{e.title}</label>)}</fieldset>;
  const fallback=path.split('.').reduce((o:any,k)=>o?.[k],initialContent)?.[0];
  return <fieldset><legend>{label}</legend>{value.map((item:any,i:number)=><div className="cms-list-item" key={item?.id??i}><div className="cms-item-heading"><strong>{item?.title||item?.name||`${label} ${i+1}`}</strong><div><Button variant="ghost" disabled={!i} onClick={()=>{const a=[...value];[a[i-1],a[i]]=[a[i],a[i-1]];onChange(a);}}>Move up</Button><Button variant="ghost" disabled={i===value.length-1} onClick={()=>{const a=[...value];[a[i+1],a[i]]=[a[i],a[i+1]];onChange(a);}}>Move down</Button><Button variant="ghost" onClick={()=>onChange(value.filter((_:any,j:number)=>j!==i))}>Remove</Button></div></div><Fields value={item} path={path+'.'+i} content={content} onUploading={onUploading} canToggleVisibility={canToggleVisibility} onChange={v=>onChange(value.map((x:any,j:number)=>i===j?v:x))}/></div>)}<Button variant="outline" onClick={()=>onChange([...value,newItem(path,value[0]??fallback)])}>Add item</Button></fieldset>;
 }
 if(value&&typeof value==='object')return <div className="cms-fields">{Object.entries(value).filter(([k])=>k!=='id').map(([k,v])=><Fields key={k} value={v} path={path+'.'+k} content={content} onUploading={onUploading} canToggleVisibility={canToggleVisibility} onChange={next=>onChange({...value,[k]:next})}/>)}</div>;
 if(typeof value==='boolean')return <label className="cms-switch"><Switch checked={value} disabled={path.includes('sections.')&&!canToggleVisibility} onCheckedChange={onChange}/>{path.includes('sections.')?'Show section after publication':label}</label>;
 if(key==='status'){const options=path.includes('offerings')?['planned','open','closed']:path.includes('entries')?['concept','pilot','live']:path.includes('projects')?['ongoing','published']:['draft','published'];return <label className="cms-field">{path.startsWith('@')?'Post visibility':label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>;}
 if(key==='category'&&path.startsWith('@'))return <label className="cms-field">Category<select value={value} onChange={e=>onChange(e.target.value)}>{content.categories.map(o=><option key={o}>{o}</option>)}</select></label>;
 const media=['image','logo'].includes(key)||path.startsWith('home.')&&key.startsWith('image')||key==='url'&&path.includes('images');
 return <label className="cms-field">{label}{typeof value==='number'?<Input type="number" min={0} value={value} onChange={e=>onChange(Number(e.target.value))}/>:<Textarea rows={['body','summary','lead'].includes(key)?5:2} value={value??''} onChange={e=>onChange(e.target.value)}/>} {media&&<><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;onUploading?.(true);try{if(file.size>8388608)throw Error('Choose an image under 8 MB.');const r=await fetch('/api/editor/upload',{method:'POST',headers:{'Content-Type':file.type,'x-filename':file.name},body:file});const d=await r.json() as {url?:string,error?:string};if(!r.ok||!d.url)throw Error(d.error||'Upload failed');onChange(d.url);}catch(err){alert(String(err));}finally{onUploading?.(false);e.target.value='';}}}/>{value&&<img className="cms-image" src={value} alt="Current image"/>}</>}</label>;
}
