'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Textarea} from '@/components/ui/textarea';
type Maintenance={enabled:boolean;message:string};
export default function SettingsView({dark,onTheme,canMaintain}:{dark:boolean;onTheme:(value:boolean)=>void;canMaintain:boolean}){
 const [maintenance,setMaintenance]=useState<Maintenance>({enabled:false,message:'We are carrying out a scheduled website update. Please check back shortly.'}),[saved,setSaved]=useState<Maintenance|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/admin/settings',{cache:'no-store'}).then(async response=>{const result=await response.json() as {maintenance:Maintenance;error?:string};if(!response.ok)throw Error(result.error);setMaintenance(result.maintenance);setSaved(result.maintenance);}).catch(error=>setError(error instanceof Error?error.message:'Unable to load settings.'));},[]);
 async function save(){setBusy(true);setError('');try{const response=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(maintenance)}),result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);setSaved(maintenance);}catch(error){setError(error instanceof Error?error.message:'Unable to save settings.');}finally{setBusy(false);}}
 return <div className="cms-simple">{error&&<p className="cms-error">{error}</p>}<h2>Workspace appearance</h2><label className="cms-switch"><Switch checked={dark} onCheckedChange={onTheme}/>Dark mode</label><p>Your preference is remembered in this browser.</p><h2>Maintenance Mode</h2><p>When enabled, visitors see this message while the CMS stays available. The website owner can still preview public pages.</p><label className="cms-switch"><Switch disabled={!canMaintain} checked={maintenance.enabled} onCheckedChange={enabled=>setMaintenance({...maintenance,enabled})}/>Temporarily close the public website</label><label className="cms-field">Visitor message<Textarea disabled={!canMaintain} rows={4} maxLength={500} value={maintenance.message} onChange={event=>setMaintenance({...maintenance,message:event.target.value})}/></label>{canMaintain?<Button disabled={busy||!saved||JSON.stringify(saved)===JSON.stringify(maintenance)} onClick={save}>Save settings</Button>:<p>Only a Super Admin can change Maintenance Mode.</p>}<h2>Publishing protection</h2><p>Every saved edit returns to Draft. An Admin must complete QA and Ready to Publish before publication or scheduling. Versions and Trash remain recoverable.</p></div>;
}
