'use client';
import {useEffect,useState} from 'react';
import {KeyRound,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PasswordInput} from '@/components/ui/password-input';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
type User={id:string;name:string;email:string;role:'superadmin'|'admin'|'editor';status:'active'|'suspended';two_factor_enabled?:number;immutable?:boolean};
type Activity={id:string;actor_name:string;actor_role:string;action:string;target_label:string;created_at:string};
async function call<T>(path:string,method='GET',body?:unknown){const r=await fetch(path,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}),d=await r.json() as T&{error?:string};if(!r.ok)throw Error(d.error||'Request failed.');return d;}
export default function UserManager({role,actorId}:{role:string;actorId:string}){
 const [users,setUsers]=useState<User[]>([]),[activity,setActivity]=useState<Activity[]>([]),[form,setForm]=useState({name:'',email:'',role:'editor',password:'',confirmPassword:''}),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resetUser,setResetUser]=useState<User|null>(null);
 async function load(){setError('');try{const [u,a]=await Promise.all([role==='editor'?Promise.resolve({items:[]}):call<{items:User[]}>('/api/admin/users'),call<{items:Activity[]}>('/api/admin/activity')]);setUsers(u.items);setActivity(a.items);}catch(e){setError(e instanceof Error?e.message:'Unable to load users.');}}
 useEffect(()=>{queueMicrotask(()=>{void load();});},[]);
 async function create(){setBusy(true);setError('');setNotice('');try{await call<Record<string,unknown>>('/api/admin/users','POST',form);setForm({name:'',email:'',role:'editor',password:'',confirmPassword:''});setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to create account.');}finally{setBusy(false);}}
 async function update(user:User,patch:Partial<User>){setBusy(true);setError('');setNotice('');try{await call<Record<string,unknown>>('/api/admin/users','PATCH',{id:user.id,role:patch.role??user.role,status:patch.status??user.status});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update account.');}finally{setBusy(false);}}
 async function resetPassword(){if(!resetUser)return;setBusy(true);setError('');setNotice('');try{const result=await call<{message:string}>('/api/admin/users/reset','POST',{id:resetUser.id});setNotice(result.message);setResetUser(null);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to send reset email.');}finally{setBusy(false);}}
 const mayReset=(user:User)=>user.id!==actorId&&!user.immutable&&user.status==='active'&&(role==='superadmin'||role==='admin'&&user.role==='editor');
 return <>{error&&<p className="cms-error" role="alert">{error}</p>}{notice&&<p className="cms-success" role="status">{notice}</p>}{role!=='editor'&&<><div className="cms-toolbar"><p>Create each CMS account with its email and initial password. Every sign-in also requires a one-time code sent to that email.</p><Button onClick={()=>setShow(!show)}>{show?'Cancel':'Add user'}</Button></div>{show&&<div className="cms-inline-form"><label>Name<Input autoComplete="off" value={form.name} maxLength={120} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<Input type="email" autoComplete="off" value={form.email} maxLength={254} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{role==='superadmin'&&<><option value="superadmin">Super Admin</option><option value="admin">Admin</option></>}<option value="editor">Editor</option></select></label><label>Initial password<PasswordInput autoComplete="new-password" minLength={12} maxLength={128} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Confirm password<PasswordInput autoComplete="new-password" minLength={12} maxLength={128} value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})}/></label><Button disabled={busy||!form.name||!form.email||form.password.length<12||form.password!==form.confirmPassword} onClick={create}>Create account</Button></div>}
 <div className="cms-table"><table><thead><tr><th>User</th><th>Role</th><th>Email OTP</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td>{u.immutable?u.role:<select disabled={busy||role==='admin'} value={u.role} onChange={e=>update(u,{role:e.target.value as User['role']})}>{['superadmin','admin','editor'].map(x=><option key={x} value={x}>{x}</option>)}</select>}</td><td>Required</td><td>{u.immutable?'Active':<select disabled={busy||role==='admin'&&u.role!=='editor'} value={u.status} onChange={e=>update(u,{status:e.target.value as User['status']})}><option value="active">Active</option><option value="suspended">Suspended</option></select>}</td><td>{mayReset(u)?<Button size="sm" variant="outline" disabled={busy} onClick={()=>setResetUser(u)}><KeyRound/>Reset password</Button>:<span>—</span>}</td></tr>)}</tbody></table></div></>}
 <Dialog open={Boolean(resetUser)} onOpenChange={open=>{if(!open&&!busy)setResetUser(null);}}><DialogContent><DialogHeader><DialogTitle>Send password reset?</DialogTitle><DialogDescription>A secure reset code and link will be emailed to {resetUser?.name}. Existing CMS sessions for this account will be signed out. You will not see or choose their new password.</DialogDescription></DialogHeader><div><strong>{resetUser?.email}</strong></div><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setResetUser(null)}>Cancel</Button><Button disabled={busy} onClick={()=>void resetPassword()}>{busy?<><LoaderCircle className="cms-spin"/>Sending…</>:<><KeyRound/>Send reset email</>}</Button></DialogFooter></DialogContent></Dialog>
 <div className="cms-subheading"><h2>{role==='editor'?'Editor activity':'Team activity'}</h2><Button variant="outline" disabled={busy} onClick={load}>Refresh</Button></div><div className="cms-table"><table><thead><tr><th>Person</th><th>Action</th><th>Content</th><th>Time</th></tr></thead><tbody>{activity.map(a=><tr key={a.id}><td>{a.actor_name}<small>{a.actor_role}</small></td><td>{a.action}</td><td>{a.target_label}</td><td>{new Date(a.created_at).toLocaleString()}</td></tr>)}</tbody></table>{!activity.length&&<p className="cms-empty">No recorded CMS activity yet.</p>}</div></>;
}
