'use client';

import {useEffect,useRef,useState} from 'react';
import {BookOpenText,BriefcaseBusiness,CalendarDays,ChartNoAxesCombined,ChevronDown,ChevronRight,ExternalLink,FilePenLine,Files,LayoutDashboard,LogOut,Megaphone,Moon,Settings,ShieldCheck,Sun,UserRound,Users} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {pages,type Section} from '@/lib/section-catalog';
import type {Content} from '@/lib/content';
import type {PostType} from '@/lib/content';
import Messages from '../editor/messages';
import Fields from './fields';
import UserManager from './user-manager';
import AnalyticsView from './analytics-view';
import SettingsView from './settings-view';
import './workspace.css';

const navigation=[['dashboard','Dashboard',LayoutDashboard],['pages','Pages',Files],['posts','Posts',FilePenLine],['analytics','Analytics',ChartNoAxesCombined],['users','Users',Users],['settings','Settings',Settings]] as const;
const statusLabels:Record<string,string>={draft:'Draft',qa:'QA Review',ready:'Ready to Publish',scheduled:'Scheduled',published:'Published',trashed:'In Trash'};
const roleLabels:Record<string,string>={superadmin:'Super Admin',admin:'Admin',editor:'Editor'};
const postTypeChoices:[PostType,string,string,typeof CalendarDays][]=[
 ['event','Event','Events, workshops, conferences and community sessions.',CalendarDays],
 ['announcement','Announcement','Official news, notices and organizational updates.',Megaphone],
 ['opportunity','Opportunity','Applications, calls, jobs, grants and open opportunities.',BriefcaseBusiness],
 ['story','Story / Publication','Community stories, articles, research and publications.',BookOpenText]
];
type Draft={key:string;status:string;revision:number;updated_at:string;updated_by:string;updated_by_name?:string;scheduled_at?:string|null;publish_error?:string|null;assigned_to?:string|null};
type Overview={actor:{id:string;name:string;email:string;role:'superadmin'|'admin'|'editor'};permissions:{approve:boolean;publish:boolean;editPages:boolean;manageUsers:boolean;maintenance:boolean};users:{id:string;name:string;email:string;role:string;status:string}[];sections:Section[];content:Content;drafts:Draft[]};
type Edit={data:Record<string,unknown>;base:Record<string,unknown>;revision:number;status:string;scheduledAt?:string|null;publishError?:string|null;assignedTo?:string|null;history:{id:string;revision:number;action:string;created_at:string}[]};

async function sectionApi(query='',method='GET',body?:unknown){
 const response=await fetch('/api/admin/sections'+query,{method,cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
 const data=await response.json() as any;if(response.status===401){location.replace('/admin/login?returnTo=%2Fadmin');throw Error('Your CMS session has expired.');}if(!response.ok)throw Error(data.error||'Request failed.');return data;
}

export default function Admin({name,email}:{name:string;email:string}){
 const [view,setView]=useState('dashboard'),[page,setPage]=useState('home'),[pagesOpen,setPagesOpen]=useState(true),[dark,setDark]=useState(false),[overview,setOverview]=useState<Overview|null>(null),[open,setOpen]=useState(''),[edit,setEdit]=useState<Edit|null>(null),[original,setOriginal]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[dashboardTab,setDashboardTab]=useState('qa'),[messages,setMessages]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null),[history,setHistory]=useState(false),[postsTab,setPostsTab]=useState('active'),[scheduleAt,setScheduleAt]=useState(''),[cmsProfile,setCmsProfile]=useState(false),[postChooser,setPostChooser]=useState(false),[selectedPostType,setSelectedPostType]=useState<PostType|null>(null);
 const request=useRef(0),dirty=!!edit&&JSON.stringify(edit.data)!==original;

 async function load(){setError('');try{setOverview(await sectionApi());}catch(e){setError(e instanceof Error?e.message:'Unable to load the CMS.');}}
 useEffect(()=>{queueMicrotask(()=>{void load();changeTheme(localStorage.getItem('somdas-cms-theme')==='dark');});},[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function changeTheme(value:boolean){setDark(value);document.documentElement.classList.toggle('dark',value);localStorage.setItem('somdas-cms-theme',value?'dark':'light');}
 function navigate(fn:()=>void){if(busy)return;if(dirty)setPending(()=>fn);else fn();}
 function go(next:string,nextPage=page){navigate(()=>{request.current++;setView(next);setPage(nextPage);setOpen('');setEdit(null);setMessages(false);setError('');setNotice('');});}
 function select(key:string){navigate(()=>{const token=++request.current;setOpen(key===open?'':key);setEdit(null);setHistory(false);setScheduleAt('');setError('');setNotice('');if(key!==open)sectionApi('?key='+encodeURIComponent(key)).then(data=>{if(token===request.current){setEdit(data);setOriginal(JSON.stringify(data.data));setScheduleAt(data.scheduledAt?new Date(data.scheduledAt).toISOString().slice(0,16):'');}}).catch(e=>{if(token===request.current)setError(e.message);});});}
 async function action(method:string,extra:Record<string,unknown>={}){if(!edit)return false;setBusy(true);setError('');setNotice('');try{await sectionApi('?key='+encodeURIComponent(open),method,{...edit,...extra});const fresh=await sectionApi('?key='+encodeURIComponent(open));setEdit(fresh);setOriginal(JSON.stringify(fresh.data));setScheduleAt(fresh.scheduledAt?new Date(fresh.scheduledAt).toISOString().slice(0,16):'');await load();setNotice(method==='PUT'?'Draft saved. Live content is unchanged.':extra.restore?'Version restored as a new draft.':'Status updated.');return true;}catch(e){setError(e instanceof Error?e.message:'Action failed.');return false;}finally{setBusy(false);}}
 async function createPost(postType:PostType){setBusy(true);setError('');try{const result=await sectionApi('?new=post','POST',{postType});setPostChooser(false);setSelectedPostType(null);await load();setView('posts');setPostsTab('active');const data=await sectionApi('?key='+encodeURIComponent(result.key));setOpen(result.key);setEdit(data);setOriginal(JSON.stringify(data.data));}catch(e){setError(e instanceof Error?e.message:'Unable to create post.');}finally{setBusy(false);}}
 async function restorePost(key:string){setBusy(true);setError('');try{const data=await sectionApi('?key='+encodeURIComponent(key));await sectionApi('?key='+encodeURIComponent(key),'POST',{revision:data.revision,restoreTrash:true});await load();setPostsTab('active');}catch(e){setError(e instanceof Error?e.message:'Unable to restore post.');}finally{setBusy(false);}}
 async function logout(){try{await fetch('/api/admin/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});}finally{location.replace('/admin/login');}}

 const currentSections=overview?.sections.filter(section=>section.page===page)??[],title=view==='pages'?pages.find(item=>item[0]===page)?.[1]:navigation.find(item=>item[0]===view)?.[1],visibleNavigation=navigation.filter(([id])=>overview?.actor.role!=='editor'||['dashboard','posts','users','settings'].includes(id));
 const queue=overview?.drafts.filter(draft=>dashboardTab==='recent'||draft.status===dashboardTab).sort((a,b)=>b.updated_at.localeCompare(a.updated_at))??[];

 function sectionEditor(section:Section){
  if(!overview)return null;const draft=overview.drafts.find(item=>item.key===section.key),visibilityPath=section.paths.find(path=>path.includes('sections.')),visible=visibilityPath?visibilityPath.split('.').reduce((value:any,key)=>value?.[key],overview.content):section.page==='posts'?overview.content.events.some(event=>event.id===section.key.slice(5)&&event.status==='published'):true;
  const isPost=section.page==='posts',canApprove=overview.permissions.approve;
  return <div className="cms-section" key={section.key}>
   <button className="cms-section-row" aria-expanded={open===section.key} onClick={()=>select(section.key)}><span>{open===section.key?<ChevronDown/>:<ChevronRight/>}{section.title}</span><span className="cms-section-status"><small>{visible?'Live':'Hidden'}</small><span className="cms-badge">{statusLabels[draft?.status??'published']}</span></span></button>
   {open===section.key&&<div className="cms-section-body">{!edit?<p>Loading section…</p>:<>
    <div className="cms-edit-meta"><span>{statusLabels[edit.status]} · Revision {edit.revision}{edit.scheduledAt?' · '+new Date(edit.scheduledAt).toLocaleString():''}</span><div><button onClick={()=>setHistory(!history)}>Version history</button>{isPost&&<Button variant="ghost" disabled={busy||dirty} onClick={async()=>{if(confirm('Move this post to Trash? It can be restored later.')&&await action('POST',{trash:true})){setOpen('');setEdit(null);}}}>Move to Trash</Button>}</div></div>
    {edit.publishError&&<p className="cms-error">Scheduled publication stopped: {edit.publishError}</p>}
    {isPost&&canApprove&&(edit.revision>0?<label className="cms-assignment">Assigned Editor<select value={edit.assignedTo??''} disabled={busy||dirty} onChange={e=>action('POST',{assignTo:e.target.value||null})}><option value="">Unassigned</option>{overview.users.filter(user=>user.role==='editor'&&user.status==='active').map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label>:<p className="cms-hint">Save the first draft before assigning this post to an Editor.</p>)}
    {history&&<div className="cms-history"><Button variant="outline" disabled={busy||dirty} onClick={()=>action('POST',{reset:true})}>Start from current live version</Button>{edit.history.length?edit.history.map(item=><div key={item.id}><span>{item.action} · {new Date(item.created_at).toLocaleString()}</span><Button variant="outline" disabled={busy||dirty} onClick={()=>action('POST',{restore:item.id})}>Restore to draft</Button></div>):<p>No saved versions yet.</p>}</div>}
    <fieldset className="cms-edit-fields" disabled={busy}>{Object.entries(edit.data).map(([path,value])=><Fields key={path} path={path} value={value} content={overview.content} onUploading={setBusy} canToggleVisibility={overview.actor.role==='superadmin'||section.page==='home'&&['home.sections.partners','home.sections.community'].includes(path)} onChange={next=>setEdit({...edit,data:{...edit.data,[path]:next}})}/>)}</fieldset>
    <div className="cms-savebar"><Button disabled={busy||!dirty} onClick={()=>action('PUT')}>Save Draft</Button><Button variant="ghost" disabled={busy||!dirty} onClick={()=>{setEdit({...edit,data:JSON.parse(original)});setNotice('Unsaved changes discarded.');}}>Cancel Changes</Button><Button variant="outline" asChild><a aria-disabled={dirty||busy} onClick={event=>{if(dirty||busy)event.preventDefault();}} href={'/api/admin/sections?key='+encodeURIComponent(open)+'&preview=1'} target="_blank" rel="noreferrer">Preview <ExternalLink/></a></Button>
     <select aria-label="Change status" value="" disabled={busy||dirty||['published','scheduled'].includes(edit.status)} onChange={event=>{if(event.target.value)action('POST',{status:event.target.value});}}><option value="">Change status</option>{edit.status==='draft'&&<option value="qa">Submit to QA Review</option>}{edit.status==='qa'&&canApprove&&<option value="ready">Mark Ready to Publish</option>}{['qa','ready'].includes(edit.status)&&<option value="draft">Return to Draft</option>}</select>
     {canApprove&&edit.status==='ready'&&<><Button disabled={busy||dirty} onClick={()=>action('POST',{status:'published'})}>Publish Now</Button><input aria-label="Schedule date and time" type="datetime-local" value={scheduleAt} onChange={event=>setScheduleAt(event.target.value)}/><Button variant="outline" disabled={busy||dirty||!scheduleAt} onClick={()=>action('POST',{status:'scheduled',publishAt:new Date(scheduleAt).toISOString()})}>Schedule</Button></>}
     {canApprove&&edit.status==='scheduled'&&<Button variant="outline" disabled={busy} onClick={()=>action('POST',{status:'draft'})}>Cancel schedule</Button>}<span className="cms-save-state">{dirty?'Unsaved changes':notice||'Saved'}</span>
    </div>
   </>}</div>}
  </div>;
 }

 if(!overview&&error)return <main className={'cms-shell access-page'+(dark?' dark':'')}><ShieldCheck/><h1>CMS access is not active</h1><p>{error}</p><a href="/admin/login">Return to secure sign-in</a></main>;
 return <SidebarProvider className={'cms-shell'+(dark?' dark':'')}><Sidebar collapsible="icon"><SidebarHeader><a className="cms-brand" href="/admin"><ShieldCheck/><span>SOMDAS<small>Content management</small></span></a></SidebarHeader><SidebarContent><SidebarGroup><SidebarMenu>{visibleNavigation.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} tooltip={label} onClick={()=>{if(id==='pages'){setPagesOpen(!pagesOpen);go('pages');}else go(id);}}><Icon/><span>{label}</span>{id==='pages'&&<ChevronDown className="ml-auto"/>}</SidebarMenuButton>{id==='pages'&&pagesOpen&&<div className="cms-page-links">{pages.map(([pageId,label])=><button key={pageId} className={view==='pages'&&page===pageId?'active':''} onClick={()=>go('pages',pageId)}>{label}</button>)}</div>}</SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><SidebarMenuButton tooltip="Sign out" onClick={()=>void logout()}><LogOut/><span>Sign out</span></SidebarMenuButton></SidebarFooter></Sidebar>
 <SidebarInset><header className="cms-topbar"><div><SidebarTrigger/><span>{title}</span></div><div><Button variant="ghost" size="icon" aria-label={dark?'Switch to light mode':'Switch to dark mode'} onClick={()=>changeTheme(!dark)}>{dark?<Sun/>:<Moon/>}</Button><a href="/" target="_blank" rel="noreferrer">View website <ExternalLink size={14}/></a><DropdownMenu><DropdownMenuTrigger asChild><button className="cms-account" aria-label="Open CMS account menu"><span>{(overview?.actor.name??name).split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><span className="cms-user">{overview?.actor.name??name}<small>{overview?roleLabels[overview.actor.role]:email}</small></span></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-64"><DropdownMenuLabel><span className="cms-menu-name">{overview?.actor.name??name}</span><small className="cms-menu-email">{overview?.actor.email??email}</small></DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>setCmsProfile(true)}><UserRound/>CMS profile</DropdownMenuItem><DropdownMenuItem onSelect={()=>void logout()}><LogOut/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
   <main className="cms-main"><div className="cms-page-heading"><div><h1>{title}</h1><p>{view==='pages'?'Choose a section to edit. Each section saves independently.':view==='dashboard'?'Review and manage website changes.':view==='posts'?'Create, assign, review and recover community posts.':''}</p></div>{view==='posts'&&<Button disabled={busy} onClick={()=>navigate(()=>{setSelectedPostType(null);setPostChooser(true);})}>Create post</Button>}{view==='pages'&&<select aria-label="Select page" value={page} onChange={event=>go('pages',event.target.value)}>{pages.map(([pageId,label])=><option key={pageId} value={pageId}>{label}</option>)}</select>}</div>
    {error&&<p className="cms-error" role="alert">{error}</p>}{!overview&&!error&&<p role="status">Loading workspace…</p>}
    {overview&&view==='dashboard'&&<><div className="cms-tabs">{[['qa','Needs Review'],['ready','Ready to Publish'],['scheduled','Scheduled'],['recent','Recent Changes']].map(([id,label])=><button key={id} className={dashboardTab===id?'active':''} onClick={()=>setDashboardTab(id)}>{label}</button>)}</div><div className="cms-table"><table><thead><tr><th>Content</th><th>Page</th><th>Status</th><th>Updated by</th><th>Last updated</th><th>Action</th></tr></thead><tbody>{queue.map(item=>{const section=overview.sections.find(candidate=>candidate.key===item.key);return <tr key={item.key}><td>{section?.title??item.key}</td><td>{pages.find(candidate=>candidate[0]===section?.page)?.[1]??'Posts'}</td><td><span className="cms-badge">{statusLabels[item.status]}</span></td><td>{item.updated_by_name??'CMS user'}</td><td>{new Date(item.updated_at).toLocaleString()}</td><td><Button variant="ghost" onClick={()=>{setView(section?.page==='posts'?'posts':'pages');setPage(section?.page??'home');if(item.status==='trashed'){setPostsTab('trash');setOpen('');setEdit(null);}else{setPostsTab('active');select(item.key);}}}>Open</Button></td></tr>;})}</tbody></table>{!queue.length&&<p className="cms-empty">No content in this queue.</p>}</div></>}
    {overview&&view==='pages'&&<>{page==='contact'&&<div className="cms-tabs"><button className={!messages?'active':''} onClick={()=>navigate(()=>setMessages(false))}>Page settings</button><button className={messages?'active':''} onClick={()=>navigate(()=>setMessages(true))}>Messages</button></div>}{messages?<Messages endpoint="/api/admin/messages"/>:currentSections.map(sectionEditor)}</>}
    {overview&&view==='posts'&&<><div className="cms-tabs"><button className={postsTab==='active'?'active':''} onClick={()=>navigate(()=>{setPostsTab('active');setOpen('');setEdit(null);})}>All posts</button><button className={postsTab==='trash'?'active':''} onClick={()=>navigate(()=>{setPostsTab('trash');setOpen('');setEdit(null);})}>Trash</button></div>{postsTab==='active'?overview.sections.filter(section=>section.page==='posts'&&overview.drafts.find(item=>item.key===section.key)?.status!=='trashed').map(sectionEditor):<div className="cms-table"><table><thead><tr><th>Post</th><th>Removed</th><th>Action</th></tr></thead><tbody>{overview.drafts.filter(item=>item.status==='trashed').map(item=><tr key={item.key}><td>{overview.sections.find(section=>section.key===item.key)?.title}</td><td>{new Date(item.updated_at).toLocaleString()}</td><td><Button variant="outline" disabled={busy} onClick={()=>restorePost(item.key)}>Restore to Draft</Button></td></tr>)}</tbody></table>{!overview.drafts.some(item=>item.status==='trashed')&&<p className="cms-empty">Trash is empty.</p>}</div>}</>}
    {overview&&view==='analytics'&&<AnalyticsView/>}
    {overview&&view==='users'&&<UserManager role={overview.actor.role} actorId={overview.actor.id}/>}
    {overview&&view==='settings'&&<SettingsView dark={dark} onTheme={changeTheme} canMaintain={overview.permissions.maintenance}/>}
   </main>
  </SidebarInset>
  <Dialog open={!!pending} onOpenChange={value=>{if(!value)setPending(null);}}><DialogContent><DialogHeader><DialogTitle>Unsaved section changes</DialogTitle><DialogDescription>Save your draft before leaving, or discard changes made since the last save.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setPending(null)}>Stay here</Button><Button variant="ghost" onClick={()=>{if(edit)setEdit({...edit,data:JSON.parse(original)});pending?.();setPending(null);}}>Discard changes</Button><Button disabled={busy} onClick={async()=>{if(await action('PUT')){pending?.();setPending(null);}}}>Save and continue</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={cmsProfile} onOpenChange={setCmsProfile}><DialogContent><DialogHeader><DialogTitle>CMS profile</DialogTitle><DialogDescription>This account is protected by a password, an email verification code and a secure CMS session.</DialogDescription></DialogHeader><dl className="cms-profile-details"><div><dt>Name</dt><dd>{overview?.actor.name??name}</dd></div><div><dt>Email</dt><dd>{overview?.actor.email??email}</dd></div><div><dt>Role</dt><dd>{overview?roleLabels[overview.actor.role]:'CMS user'}</dd></div><div><dt>Email verification</dt><dd>Enabled</dd></div></dl><DialogFooter><Button variant="outline" onClick={()=>setCmsProfile(false)}>Close</Button><Button onClick={()=>void logout()}>Sign out</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={postChooser} onOpenChange={value=>{if(!busy){setPostChooser(value);if(!value)setSelectedPostType(null);}}}><DialogContent className="cms-post-type-dialog"><DialogHeader><DialogTitle>Choose post type</DialogTitle><DialogDescription>Select what you want to publish. The next form will show only the fields needed for that post type.</DialogDescription></DialogHeader><div className="cms-post-types" role="radiogroup" aria-label="Post type">{postTypeChoices.map(([id,label,description,Icon])=><button key={id} type="button" role="radio" aria-checked={selectedPostType===id} className={selectedPostType===id?'selected':''} onClick={()=>setSelectedPostType(id)}><Icon/><span><strong>{label}</strong><small>{description}</small></span></button>)}</div><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setPostChooser(false)}>Cancel</Button><Button disabled={!selectedPostType||busy} onClick={()=>selectedPostType&&createPost(selectedPostType)}>{busy?'Creating…':'Continue'}</Button></DialogFooter></DialogContent></Dialog>
 </SidebarProvider>;
}
