import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import {build} from 'esbuild';
mkdirSync('work',{recursive:true});
await build({stdin:{contents:"export * from './lib/cms-auth'; export * from './lib/cms-access';",resolveDir:process.cwd(),loader:'ts'},outfile:'work/cms-auth-test.mjs',bundle:true,platform:'node',format:'esm'});
const {cmsAuthApi,getCMSActor,hashCMSPassword}=await import('../work/cms-auth-test.mjs');
function env(){const sqlite=new DatabaseSync(':memory:');for(const entry of JSON.parse(readFileSync('drizzle/meta/_journal.json')).entries)sqlite.exec(readFileSync('drizzle/'+entry.tag+'.sql','utf8'));const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this;},first(){return sqlite.prepare(sql).get(...args)||null;},all(){return {results:sqlite.prepare(sql).all(...args)};},run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};},batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(statement=>statement.run());sqlite.exec('COMMIT');return result;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};return {DB,BUCKET:{},CMS_AUTH_SECRET:'test-only-cms-auth-secret',RESEND_API_KEY:'re_test',AUTH_EMAIL_FROM:'SOMDAS <no-reply@somdas.org>'};}
function req(path,data,headers={}){return new Request('https://somdas.test'+path,{method:data===undefined?'GET':'POST',headers:{...headers,...data!==undefined?{Origin:'https://somdas.test','Content-Type':'application/json'}:{}},body:data===undefined?undefined:JSON.stringify(data)});}
function emailBox(){const sent=[];const previous=globalThis.fetch;globalThis.fetch=async(_url,options)=>{sent.push(JSON.parse(options.body));return new Response(JSON.stringify({id:'email-id'}),{status:200});};return {sent,restore(){globalThis.fetch=previous;},lastCode(){const match=sent.at(-1)?.html.match(/>(\d{6})<\/div>/);assert.ok(match,'email contains a code');return match[1];},lastToken(){const match=sent.at(-1)?.html.match(/[?&]token=([^"&]+)/);assert.ok(match,'reset email contains a token');return decodeURIComponent(match[1]);}};}

test('owner bootstrap sends a Gmail code and requires password plus email OTP',async()=>{const box=emailBox();try{const e=env();let response=await cmsAuthApi(req('/api/admin/auth/bootstrap',{},{}),e);assert.equal(response.status,403);response=await cmsAuthApi(req('/api/admin/auth/bootstrap',{}, {'oai-authenticated-user-id':'owner-platform-id','oai-authenticated-user-email':'yusufabdisalamyusuf@gmail.com'}),e);assert.equal(response.status,200);const setup=await response.json();assert.equal(box.sent[0].to[0],'yusufabdisalamyusuf@gmail.com');assert.match(setup.maskedEmail,/^yu/);response=await cmsAuthApi(req('/api/admin/auth/owner-setup',{challengeToken:setup.challengeToken,password:'Secure-owner-pass-123',confirmPassword:'Secure-owner-pass-123',code:box.lastCode()}),e);assert.equal(response.status,200,await response.clone().text());const cookie=response.headers.get('set-cookie').split(';')[0];assert.match(cookie,/^__Host-somdas_cms_session=/);const session=await (await cmsAuthApi(req('/api/admin/auth/session',undefined,{Cookie:cookie}),e)).json();assert.equal(session.authenticated,true);assert.equal(session.user.role,'superadmin');const blocked=await getCMSActor(e.DB,new Headers({'oai-authenticated-user-id':'owner-platform-id','oai-authenticated-user-email':'yusufabdisalamyusuf@gmail.com'}));assert.equal(blocked,null);}finally{box.restore();}});

test('every CMS login requires password followed by an emailed one-time code',async()=>{const box=emailBox();try{const e=env(),now=new Date().toISOString(),password='Temporary-pass-123';e.DB.prepare("INSERT INTO cms_users (id,platform_id,name,email,role,status,password_hash,two_factor_secret,two_factor_enabled,created_at,updated_at,created_by) VALUES ('editor',NULL,'Hodan','hodan@somdas.org','editor','active',?,NULL,0,?,?, 'owner')").bind(await hashCMSPassword(password),now,now).run();let response=await cmsAuthApi(req('/api/admin/auth/login',{email:'hodan@somdas.org',password}),e),login=await response.json();assert.equal(login.requiresEmailCode,true);assert.equal(box.sent[0].to[0],'hodan@somdas.org');const correctCode=box.lastCode(),wrongCode=correctCode==='000000'?'111111':'000000';response=await cmsAuthApi(req('/api/admin/auth/verify',{challengeToken:login.challengeToken,code:wrongCode}),e);assert.equal(response.status,400);response=await cmsAuthApi(req('/api/admin/auth/verify',{challengeToken:login.challengeToken,code:correctCode}),e);assert.equal(response.status,200,await response.clone().text());}finally{box.restore();}});

test('email reset changes the password and revokes previous CMS sessions',async()=>{const box=emailBox();try{const e=env(),now=new Date().toISOString(),oldPassword='Temporary-pass-123',newPassword='Replacement-pass-456';e.DB.prepare("INSERT INTO cms_users (id,platform_id,name,email,role,status,password_hash,two_factor_secret,two_factor_enabled,created_at,updated_at,created_by) VALUES ('admin',NULL,'Amina','amina@somdas.org','admin','active',?,NULL,1,?,?, 'owner')").bind(await hashCMSPassword(oldPassword),now,now).run();let response=await cmsAuthApi(req('/api/admin/auth/login',{email:'amina@somdas.org',password:oldPassword}),e),login=await response.json();response=await cmsAuthApi(req('/api/admin/auth/verify',{challengeToken:login.challengeToken,code:box.lastCode()}),e);const oldCookie=response.headers.get('set-cookie').split(';')[0];response=await cmsAuthApi(req('/api/admin/auth/reset/request',{email:'amina@somdas.org'}),e);assert.equal(response.status,200);const token=box.lastToken(),code=box.lastCode();response=await cmsAuthApi(req('/api/admin/auth/reset/confirm',{challengeToken:token,code,password:newPassword,confirmPassword:newPassword}),e);assert.equal(response.status,200,await response.clone().text());const oldSession=await (await cmsAuthApi(req('/api/admin/auth/session',undefined,{Cookie:oldCookie}),e)).json();assert.equal(oldSession.authenticated,false);assert.equal((await cmsAuthApi(req('/api/admin/auth/login',{email:'amina@somdas.org',password:oldPassword}),e)).status,401);const newLogin=await cmsAuthApi(req('/api/admin/auth/login',{email:'amina@somdas.org',password:newPassword}),e);assert.equal(newLogin.status,200);}finally{box.restore();}});
