import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import {build} from 'esbuild';
import {createHash} from 'node:crypto';
mkdirSync('work',{recursive:true});
await build({stdin:{contents:"export * from './lib/cms-api'; export * from './lib/contact-api'; export * from './lib/storage'; export * from './lib/content'; export * from './lib/render'; export * from './lib/about-render'; export * from './lib/about-content'; export * from './lib/sodi-content'; export * from './lib/sodi-render'; export * from './lib/ai-research-content'; export * from './lib/ai-research-render'; export * from './lib/academy-content'; export * from './lib/academy-render'; export * from './lib/program-pages-content'; export * from './lib/program-pages-render'; export * from './lib/member-auth'; export * from './lib/profile-render';",resolveDir:process.cwd(),loader:'ts'},outfile:'work/cms-test.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'raw-html',setup(b){b.onResolve({filter:/\.html\?raw$/},a=>({path:new URL(a.path,'file://'+a.resolveDir+'/').pathname.replace(/\?raw$/,''),namespace:'raw'}));b.onLoad({filter:/.*/,namespace:'raw'},a=>({contents:readFileSync(a.path,'utf8'),loader:'text'}));}}]});
const cms=await import('../work/cms-test.mjs');
const ownerToken='cms-owner-test-token';
const owner={Cookie:'__Host-somdas_cms_session='+ownerToken,Origin:'https://somdas.test'};
test('homepage uploads follow section visibility and old clients cannot erase new homepage fields',async()=>{const e=env(),c=structuredClone(cms.initialContent),id=crypto.randomUUID(),url='/media/'+id,key=Object.keys(c.home.hero).find(k=>k.startsWith('image'));await e.BUCKET.put(id,new Uint8Array([1]),{httpMetadata:{contentType:'image/png'}});c.home.hero[key]=url;await cms.saveContent(e.DB,c,0,'owner');assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,200);assert.ok(cms.renderHome(c).includes('src="'+url+'"'));c.sections.hero=false;await cms.saveContent(e.DB,c,1,'owner');assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,404);delete c.home;assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:c,revision:2}),e)).status,409);});
const request=(path,method='GET',body,headers=owner)=>new Request('https://somdas.test'+path,{method,headers:{...headers,...body?{'Content-Type':'application/json'}:{}},body:body?JSON.stringify(body):undefined});
// Migration filename is read from the schema journal, preserving immutable migration names.
function env(){const db=new DatabaseSync(':memory:');const journal=JSON.parse(readFileSync('drizzle/meta/_journal.json'));for(const entry of journal.entries)db.exec(readFileSync('drizzle/'+entry.tag+'.sql','utf8'));const now=new Date().toISOString(),expires=new Date(Date.now()+3600000).toISOString(),hash=createHash('sha256').update(ownerToken).digest('hex');db.prepare("INSERT INTO cms_users (id,platform_id,name,email,role,status,password_hash,two_factor_secret,two_factor_enabled,created_at,updated_at,created_by) VALUES ('owner',NULL,'Yusuf Abdisalam','yusufabdisalamyusuf@gmail.com','superadmin','active','test','test',1,?,?, 'owner')").run(now,now);db.prepare('INSERT INTO cms_sessions (token_hash,user_id,expires_at,created_at,last_seen_at) VALUES (?,\'owner\',?,?,?)').run(hash,expires,now,now);const files=new Map();const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};},async batch(statements){const results=[];for(const statement of statements)results.push(await statement.run());return results;}};return {DB,BUCKET:{async put(id,data,options){files.set(id,{body:data,httpMetadata:options.httpMetadata});},async get(id){return files.get(id);},async delete(id){files.delete(id);}}};}
test('server rejects anonymous, fake identity headers and cross-origin writes',async()=>{const e=env();assert.equal((await cms.cmsApi(request('/api/editor/content','GET',null,{}),e)).status,401);assert.equal((await cms.cmsApi(request('/api/editor/content','GET',null,{'oai-authenticated-user-id':'fake','oai-authenticated-user-email':'yusufabdisalamyusuf@gmail.com'}),e)).status,401);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:cms.initialContent,revision:0},{...owner,Origin:'https://other.test'}),e)).status,403);});
test('D1 saves survive new reads and stale revisions cannot overwrite changes',async()=>{const e=env();const c=structuredClone(cms.initialContent);c.communityTitle='Saved title';assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:c,revision:0}),e)).status,200);const saved=await (await cms.cmsApi(request('/api/editor/content'),e)).json();assert.equal(saved.content.communityTitle,'Saved title');assert.equal(saved.revision,1);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:c,revision:0}),e)).status,409);c.communityTitle='Updated';assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:c,revision:1}),e)).status,200);assert.equal((await cms.readContent(e.DB)).content.communityTitle,'Updated');});
test('partners are empty and hidden; every disabled section and its links disappear',()=>{const c=structuredClone(cms.initialContent);assert.equal(c.partners.length,0);assert.ok(!cms.renderHome(c).includes('id="partners"'));for(const id of Object.keys(c.sections)){c.sections[id]=false;const html=cms.renderHome(c);assert.ok(!html.includes(`id="${id}"`),id);assert.ok(!html.includes(`href="#${id}"`),id);}});
test('partner section renders only original logo assets in a centered minimal grid',()=>{const c=structuredClone(cms.initialContent);c.sections.partners=true;c.partners=[{id:crypto.randomUUID(),name:'Logo partner',logo:'/assets/partner-dsa.png',url:'https://example.com'},{id:crypto.randomUUID(),name:'No logo yet',logo:'',url:''}];const html=cms.renderHome(c);assert.ok(html.includes('class="partners-heading"'));assert.ok(html.includes('class="partner-logo"'));assert.ok(html.includes('alt="Logo partner"'));assert.ok(!html.includes('No logo yet'));assert.ok(!html.includes('class="partner-name"'));});
test('homepage sections follow the editor order',()=>{const c=structuredClone(cms.initialContent);c.sections.partners=true;c.partners=[{id:crypto.randomUUID(),name:'Partner',logo:'/assets/partner-dsa.png',url:''}];c.sectionOrder=['hero','community','our-programs','sodi-flagship','about','focus','partners','get-involved'];const html=cms.renderHome(c);assert.ok(html.indexOf('id="community"')<html.indexOf('id="our-programs"'));assert.ok(html.indexOf('id="focus"')<html.indexOf('id="partners"'));const invalid=structuredClone(c);invalid.sectionOrder[1]='hero';assert.equal(cms.contentSchema.safeParse(invalid).success,false);});
test('published stories, categories, pagination and featured order stay independent',()=>{const c=structuredClone(cms.initialContent);for(let i=0;i<12;i++)c.events.push({...c.events[2],id:'story-'+i,title:'Story '+i,date:'2026-09-'+String(i+1).padStart(2,'0')});c.featured=['story-1','story-3','story-2'];const home=cms.renderHome(c);assert.ok(home.includes('class="community-mosaic community-mosaic-count-4"'));assert.ok(home.indexOf('Story 1')<home.indexOf('Story 3'));assert.ok(home.indexOf('Story 3')<home.indexOf('Story 2'));assert.ok(!home.includes('Research conversations at HUMC'));const html=cms.renderActivities(c,new URL('https://somdas.test/activities?category=Conferences'));assert.ok(!html.includes('Research conversations at HUMC'));assert.ok(html.includes('No published stories'));const page=cms.renderActivities(c,new URL('https://somdas.test/activities?page=2'));assert.ok(page.includes('Page 2 of 2'));assert.equal((page.match(/class="activity-card"/g)||[]).length,4);});
test('validation forbids too many picks, draft picks, unsafe links and incomplete publication',()=>{const c=structuredClone(cms.initialContent);assert.equal(cms.contentSchema.safeParse(c).success,true);c.featured=['humc-2026'];assert.equal(cms.contentSchema.safeParse(c).success,false);c.featured=Array(4).fill('telecom-hackathon-2026');assert.equal(cms.contentSchema.safeParse(c).success,false);c.featured=[];c.events[0].status='published';assert.equal(cms.contentSchema.safeParse(c).success,false);c.events[0].status='draft';c.partners=[{id:crypto.randomUUID(),name:'Unsafe',logo:'',url:'javascript:alert(1)'}];assert.equal(cms.contentSchema.safeParse(c).success,false);});
test('story content is escaped',()=>{const event={...cms.initialContent.events[2],title:'<script>alert(1)</script>',body:'<img src=x onerror=alert(1)>'};const html=cms.renderEvent(event);assert.ok(!html.includes('<script>alert'));assert.ok(html.includes('&lt;img'));});
test('uploads are validated, stored, private in draft, and visible when published',async()=>{const e=env();const bad=new Request('https://somdas.test/api/editor/upload',{method:'POST',headers:{...owner,'Content-Type':'image/png'},body:'not an image'});assert.equal((await cms.cmsApi(bad,e)).status,400);const bytes=Uint8Array.from([137,80,78,71,13,10,26,10,0]);const req=new Request('https://somdas.test/api/editor/upload',{method:'POST',headers:{...owner,'Content-Type':'image/png'},body:bytes});const res=await cms.cmsApi(req,e);assert.equal(res.status,201);const {url}=await res.json();assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,404);assert.equal((await cms.serveMedia(request(url),e)).status,200);const c=structuredClone(cms.initialContent);c.events[2].images=[{url,alt:'Test image'}];await cms.saveContent(e.DB,c,0,'owner');assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,200);});


test('legacy documents gain About defaults without losing saved homepage content',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.about;old.communityTitle='Previously saved title';await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.communityTitle,'Previously saved title');assert.equal(loaded.content.about.vision.title,'Our Vision');assert.equal(loaded.revision,1);});
test('contact settings migrate safely and official links render without placeholders',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.contact;await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.contact.email,'info@somdas.org');let html=cms.renderHome(loaded.content);assert.ok(html.includes('mailto:info@somdas.org'));assert.ok(!html.includes('aria-label="Facebook"'));loaded.content.contact.facebook='https://facebook.com/somdas';html=cms.renderHome(loaded.content);assert.ok(html.includes('aria-label="Facebook"'));loaded.content.contact.facebook='javascript:alert(1)';assert.equal(cms.contentSchema.safeParse(loaded.content).success,false);});
test('homepage removes the SODI caption and includes complete member account forms',()=>{const html=cms.renderHome(cms.initialContent),authCss=readFileSync('public/auth.css','utf8');assert.ok(!html.includes('Open data. Shared possibilities.'));assert.ok(!html.includes('Pause animation'));assert.ok(html.includes('id="auth-dialog"'));assert.ok(html.includes('class="auth-dialog-mark"'));assert.ok(html.includes('<img src="/assets/somdas-mark.png"'));assert.ok(!html.includes('class="auth-dialog-mark" aria-hidden="true">S'));assert.ok(html.includes('data-auth-form="login"'));assert.ok(html.includes('data-auth-form="register"'));assert.ok(html.includes('data-auth-form="forgot"'));assert.ok(html.includes('data-profile-menu hidden'));assert.ok(html.includes('data-mobile-profile hidden'));assert.equal((html.match(/data-auth-logout/g)||[]).length,2);assert.match(authCss,/\.auth-actions\[hidden\].*display:none!important/);assert.match(authCss,/\[data-profile-image\]\[hidden\]/);assert.ok(html.includes('href="/privacy"'));assert.ok(html.includes('href="/terms"'));assert.ok(!html.includes('Continue with Google'));});

test('homepage uses the current CMS and contains no obsolete contact dialog',()=>{const html=cms.renderHome(cms.initialContent);assert.ok(html.includes('href="/admin">Content manager</a>'));assert.ok(!html.includes('id="contact-dialog"'));assert.ok(html.includes('aria-label="SOMDAS account"'));});

test('member registration creates a secure session and profile update persists',async()=>{const e=env();const registration=await cms.memberAuthApi(request('/api/auth/register','POST',{name:'Amina Ali',email:'AMINA@example.com',password:'strong-pass-123',confirmPassword:'strong-pass-123'}),e);assert.equal(registration.status,201);assert.ok(registration.headers.get('set-cookie').startsWith('__Host-somdas_session='));assert.ok(registration.headers.get('set-cookie').includes('HttpOnly'));const cookie=registration.headers.get('set-cookie').split(';')[0];const session=await (await cms.memberAuthApi(request('/api/auth/session','GET',null,{Cookie:cookie}),e)).json();assert.equal(session.authenticated,true);assert.equal(session.user.email,'amina@example.com');const profile=await cms.memberAuthApi(request('/api/auth/profile','PATCH',{name:'Amina Hassan'},{...owner,Cookie:cookie}),e);assert.equal(profile.status,200);assert.equal((await profile.json()).user.name,'Amina Hassan');});

test('full profile supports private avatar storage and protected permanent deletion',async()=>{const e=env();const registration=await cms.memberAuthApi(request('/api/auth/register','POST',{name:'Amina Ali',email:'amina@example.com',password:'strong-pass-123',confirmPassword:'strong-pass-123'}),e),cookie=registration.headers.get('set-cookie').split(';')[0];const image=Uint8Array.from([137,80,78,71,13,10,26,10,0]);const upload=await cms.memberAuthApi(new Request('https://somdas.test/api/auth/avatar',{method:'POST',headers:{Origin:'https://somdas.test',Cookie:cookie,'Content-Type':'image/png'},body:image}),e);assert.equal(upload.status,200,await upload.clone().text());const uploaded=await upload.json();assert.match(uploaded.user.avatarUrl,/^\/api\/auth\/avatar\?v=/);const avatar=await cms.memberAuthApi(new Request('https://somdas.test/api/auth/avatar',{headers:{Cookie:cookie}}),e);assert.equal(avatar.status,200);assert.equal(avatar.headers.get('content-type'),'image/png');const weakDelete=await cms.memberAuthApi(request('/api/auth/account','DELETE',{currentPassword:'strong-pass-123',confirmation:'delete'},{...owner,Cookie:cookie}),e);assert.equal(weakDelete.status,400);const deletion=await cms.memberAuthApi(request('/api/auth/account','DELETE',{currentPassword:'strong-pass-123',confirmation:'DELETE'},{...owner,Cookie:cookie}),e);assert.equal(deletion.status,200);assert.ok(deletion.headers.get('set-cookie').includes('Max-Age=0'));const session=await (await cms.memberAuthApi(request('/api/auth/session','GET',null,{Cookie:cookie}),e)).json();assert.equal(session.authenticated,false);});

test('profile page presents account controls as confirmation dialogs',()=>{const html=cms.renderProfile(cms.initialContent,{id:'member-1',name:'Amina Ali',email:'amina@example.com',createdAt:'2026-09-01T00:00:00.000Z',avatarUrl:'/api/auth/avatar?v=1'});assert.ok(html.includes('Profile &amp; security'));assert.ok(html.includes('id="profile-password-dialog"'));assert.ok(!html.includes('id="profile-reset-dialog"'));assert.ok(html.includes('id="profile-signout-dialog"'));assert.ok(html.includes('id="profile-delete-dialog"'));assert.ok(html.includes('data-profile-forgot'));assert.ok(html.includes('data-profile-camera'));assert.ok(html.includes('data-profile-upload'));assert.ok(html.includes('data-crop-save'));assert.ok(html.includes('Type DELETE to confirm'));assert.ok(html.includes('/profile.js'));assert.ok(html.includes('/profile.css'));});

test('member auth rejects cross-site, non-JSON and oversized requests and throttles login guessing',async()=>{const e=env();const url='https://somdas.test/api/auth/login';assert.equal((await cms.memberAuthApi(new Request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),e)).status,403);assert.equal((await cms.memberAuthApi(new Request(url,{method:'POST',headers:{Origin:'https://somdas.test','Content-Type':'text/plain'},body:'hello'}),e)).status,415);assert.equal((await cms.memberAuthApi(new Request(url,{method:'POST',headers:{Origin:'https://somdas.test','Content-Type':'application/json'},body:'x'.repeat(17000)}),e)).status,413);let last;for(let i=0;i<11;i++)last=await cms.memberAuthApi(request('/api/auth/login','POST',{email:'missing@example.com',password:'not-the-password'}),e);assert.equal(last.status,429);});

test('media endpoint only permits safe read methods',async()=>{const e=env(),id=crypto.randomUUID();assert.equal((await cms.serveMedia(request('/media/'+id,'POST',{}),e)).status,405);});
test('About sections hide fully, statements escape text, team order and visibility are respected',()=>{const c=structuredClone(cms.initialContent);c.about.team=[{id:crypto.randomUUID(),name:'Person One',role:'Founder',bio:'First biography',image:'',imageAlt:'',linkedin:'',visible:true},{id:crypto.randomUUID(),name:'Person Hidden',role:'',bio:'',image:'',imageAlt:'',linkedin:'',visible:false},{id:crypto.randomUUID(),name:'Person Two',role:'Research lead',bio:'Second biography',image:'',imageAlt:'',linkedin:'',visible:true}];c.about.vision.lead='<script>bad()</script>';let html=cms.renderAbout(c);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('Person Hidden'));assert.ok(html.indexOf('Person One')<html.indexOf('Person Two'));assert.ok(html.includes('class="about-team-grid"'));assert.ok(html.includes('href="/about" aria-current="page"'));for(const key of Object.keys(c.about.sections)){c.about.sections[key]=false;html=cms.renderAbout(c);assert.ok(!html.includes('id="about-'+key+'"'),key);}});
test('About changes persist and older editor requests cannot discard them',async()=>{const e=env();const c=structuredClone(cms.initialContent);c.about.mission.body='Our updated mission';c.about.sections.vision=false;const save=await cms.cmsApi(request('/api/editor/content','PUT',{content:c,revision:0}),e);assert.equal(save.status,200);const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.about.mission.body,'Our updated mission');assert.equal(loaded.content.about.sections.vision,false);const old=structuredClone(c);delete old.about;assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:old,revision:1}),e)).status,409);});
test('team media is visible only for published profiles and rejects unsafe links',async()=>{const e=env();const bytes=Uint8Array.from([137,80,78,71,13,10,26,10,0]);const response=await cms.cmsApi(new Request('https://somdas.test/api/editor/upload',{method:'POST',headers:{...owner,'Content-Type':'image/png'},body:bytes}),e);const {url}=await response.json();const c=structuredClone(cms.initialContent);c.about.team=[{id:crypto.randomUUID(),name:'Owner profile',role:'Founder',bio:'Biography',image:url,imageAlt:'Profile',linkedin:'',visible:false}];await cms.saveContent(e.DB,c,0,'owner');assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,404);c.about.team[0].visible=true;await cms.saveContent(e.DB,c,1,'owner');assert.equal((await cms.serveMedia(request(url,'GET',null,{}),e)).status,200);c.about.team[0].linkedin='javascript:alert(1)';assert.equal(cms.contentSchema.safeParse(c).success,false);});

test('SODI defaults preserve existing content and old clients cannot remove SODI settings',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.sodi;old.about.vision.title='Saved vision';await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.about.vision.title,'Saved vision');assert.equal(loaded.content.sodi.platformReady,false);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:old,revision:1}),e)).status,409);loaded.content.sodi.hero.title='Edited SODI heading';loaded.content.sodi.sections.process=false;assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:loaded.content,revision:1}),e)).status,200);assert.equal((await cms.readContent(e.DB)).content.sodi.hero.title,'Edited SODI heading');});
test('SODI visibility, platform link validation and category links',()=>{const c=structuredClone(cms.initialContent);c.sodi.platformReady=true;assert.equal(cms.contentSchema.safeParse(c).success,false);c.sodi.platformUrl='https://sodi.example.org';c.sodi.categories[0].url='https://sodi.example.org/health';let html=cms.renderSodi(c);assert.ok(html.includes('href="https://sodi.example.org/health"'));c.sodi.categories[0].visible=false;html=cms.renderSodi(c);assert.ok(!html.includes('href="https://sodi.example.org/health"'));for(const id of Object.keys(c.sodi.sections)){c.sodi.sections[id]=false;assert.ok(!cms.renderSodi(c).includes('id="sodi-'+id+'"'),id);}c.sodi.platformUrl='javascript:alert(1)';assert.equal(cms.contentSchema.safeParse(c).success,false);});

test('AI & Research defaults migrate safely and every section is editor controlled',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.aiResearch;old.communityTitle='Keep this';await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.communityTitle,'Keep this');assert.equal(loaded.content.aiResearch.focusAreas.length,5);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:old,revision:1}),e)).status,409);const c=structuredClone(cms.initialContent);let html=cms.renderAiResearch(c);assert.ok(html.includes('/assets/program-research-dashboard.png'));assert.ok(html.includes('Research will be added as it is ready.'));assert.ok(html.includes('research-programs'));for(const id of Object.keys(c.aiResearch.sections)){c.aiResearch.sections[id]=false;html=cms.renderAiResearch(c);assert.ok(!html.includes(`id="research-${id}"`),id);}});

test('Academy defaults migrate safely and sections and opportunities are editor controlled',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.academy;await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.academy.pathways.length,4);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:old,revision:1}),e)).status,409);const c=structuredClone(cms.initialContent);let html=cms.renderAcademy(c);assert.ok(html.includes('/assets/program-academy-dashboard.png'));assert.ok(html.includes('No open course is being advertised yet.'));for(const id of Object.keys(c.academy.sections)){c.academy.sections[id]=false;html=cms.renderAcademy(c);assert.ok(!html.includes(`id="academy-${id}"`),id);}});

test('SOMDAS Lab and Solutions migrate independently and every section is controlled',async()=>{const e=env();const old=structuredClone(cms.initialContent);delete old.lab;delete old.solutions;await cms.saveContent(e.DB,old,0,'owner');const loaded=await cms.readContent(e.DB);assert.equal(loaded.content.lab.services.length,4);assert.equal(loaded.content.solutions.services.length,5);assert.equal((await cms.cmsApi(request('/api/editor/content','PUT',{content:old,revision:1}),e)).status,409);for(const [key,render,prefix,asset] of [['lab',cms.renderLab,'lab','program-lab-dashboard.png'],['solutions',cms.renderSolutions,'solutions','program-digital-dashboard.png']]){const c=structuredClone(cms.initialContent);let html=render(c);assert.ok(html.includes(asset));assert.ok(html.includes('Nothing is being presented as finished yet.'));for(const id of Object.keys(c[key].sections)){c[key].sections[id]=false;html=render(c);assert.ok(!html.includes(`id="${prefix}-${id}"`),`${key}:${id}`);}}});

test('contact messages persist privately, validate input and throttle repeat submissions',async()=>{const e=env();const body={name:'Visitor',email:'visitor@example.com',topic:'General enquiry',message:'A research collaboration question.',website:''};
assert.equal((await cms.contactApi(request('/api/contact','POST',body,{Origin:'https://other.test'}),e.DB)).status,403);
assert.equal((await cms.contactApi(request('/api/contact','POST',{...body,email:'bad'}),e.DB)).status,400);
assert.equal((await cms.contactApi(request('/api/contact','POST',body),e.DB)).status,201);
assert.equal((await cms.cmsApi(request('/api/editor/messages','GET',null,{}),e)).status,401);
const inbox=await (await cms.cmsApi(request('/api/editor/messages'),e)).json();assert.equal(inbox.messages.length,1);assert.equal(inbox.messages[0].message,body.message);
await cms.contactApi(request('/api/contact','POST',body),e.DB);await cms.contactApi(request('/api/contact','POST',body),e.DB);
assert.equal((await cms.contactApi(request('/api/contact','POST',body),e.DB)).status,429);
});
