import assert from 'node:assert/strict';
import test from 'node:test';
import worker from '../dist/server/index.js';
const env={DB:{prepare(){return {async first(){return null;}};}},ASSETS:{fetch:async()=>new Response('Not found',{status:404})}};
const ctx={waitUntil(){},passThroughOnException(){}};
test('built Worker serves updated homepage with hidden partners and dynamic stories',async()=>{const response=await worker.fetch(new Request('https://somdas.test/'),env,ctx);assert.equal(response.status,200);assert.ok(response.headers.get('content-security-policy')?.includes("default-src 'self'"));assert.equal(response.headers.get('x-frame-options'),'DENY');assert.ok(response.headers.get('permissions-policy')?.includes('camera=()'));const html=await response.text();assert.ok(html.includes('Building a Future'));assert.ok(html.includes('Research &amp; AI'));assert.ok(!html.includes('id="partners"'));assert.ok(html.includes('AI for Telecom Network'));assert.ok(html.includes('/community'));});

test('built Worker redirects favicon and rejects writes to public pages',async()=>{const icon=await worker.fetch(new Request('https://somdas.test/favicon.ico'),env,ctx);assert.equal(icon.status,308);assert.equal(icon.headers.get('location'),'https://somdas.test/assets/somdas-mark.png');const write=await worker.fetch(new Request('https://somdas.test/about',{method:'POST'}),env,ctx);assert.equal(write.status,405);assert.equal(write.headers.get('allow'),'GET, HEAD');});
test('built Worker never exposes draft event to visitors',async()=>{const res=await worker.fetch(new Request('https://somdas.test/community/humc-2026?preview=1'),env,ctx);assert.equal(res.status,404);});
test('built Worker does not accept platform identity headers as a CMS session',async()=>{const res=await worker.fetch(new Request('https://somdas.test/community/humc-2026?preview=1',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'yusufabdisalamyusuf@gmail.com'}}),env,ctx);assert.equal(res.status,404);});
test('Community is a top-level page and old activity URLs redirect safely',async()=>{const res=await worker.fetch(new Request('https://somdas.test/community'),env,ctx);assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('Community, events &amp; updates'));assert.ok(html.includes('<h1>Community &amp; activities</h1>'));assert.ok(html.includes('href="/community" aria-current="page"'));assert.ok(!html.includes('community-network'));assert.ok(html.includes('#community-stories'));assert.ok(html.includes('/community/telecom-hackathon-2026'));const old=await worker.fetch(new Request('https://somdas.test/activities/telecom-hackathon-2026'),env,ctx);assert.equal(old.status,308);assert.equal(old.headers.get('location'),'https://somdas.test/community/telecom-hackathon-2026');});
test('legacy editor route returns to the protected CMS',async()=>{const res=await worker.fetch(new Request('https://somdas.test/editor'),env,ctx);assert.equal(res.status,308);assert.equal(res.headers.get('location'),'https://somdas.test/admin');});
test('CMS pages require a CMS session and the login page remains reachable',async()=>{const protectedPage=await worker.fetch(new Request('https://somdas.test/admin',{headers:{'oai-authenticated-user-id':'id','oai-authenticated-user-email':'yusufabdisalamyusuf@gmail.com'}}),env,ctx);assert.equal(protectedPage.status,303);assert.equal(protectedPage.headers.get('location'),'https://somdas.test/admin/login?returnTo=%2Fadmin');const login=await worker.fetch(new Request('https://somdas.test/admin/login'),env,ctx);assert.equal(login.status,200);assert.ok((await login.text()).includes('Checking secure access'));});

test('built Worker serves the About page with independent Vision and Mission sections',async()=>{const res=await worker.fetch(new Request('https://somdas.test/about'),env,ctx);assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('id="about-vision"'));assert.ok(html.includes('id="about-mission"'));assert.ok(html.includes('/assets/about-banner.png'));assert.ok(html.includes('/about.css'));assert.ok(!html.includes('Name to be added'));});

test('SODI and linked program introductions resolve with permanent numbers',async()=>{for(const slug of ['sodi','ai-research','academy','innovation-lab','digital-solutions']){const res=await worker.fetch(new Request('https://somdas.test/programs/'+slug),env,ctx);assert.equal(res.status,200,slug);const html=await res.text();assert.ok(html.includes('You’re here'));if(slug==='sodi'){assert.ok(html.includes('/assets/sodi-hero-catalog.png'));assert.ok(html.includes('/assets/program-sodi-dashboard.png'));assert.ok(!html.includes('Platform preview · In development'));assert.ok(html.includes('Planned category'));assert.ok(html.includes('sodi-hero-lines'));}if(slug==='innovation-lab')assert.ok(!html.includes('Prototype workspace · illustrative view'));}const alias=await worker.fetch(new Request('https://somdas.test/sodi'),env,ctx);assert.equal(alias.status,308);assert.equal(alias.headers.get('location'),'https://somdas.test/programs/sodi');});

test('AI & Research route serves the full designed page',async()=>{const res=await worker.fetch(new Request('https://somdas.test/programs/ai-research'),env,ctx);assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('id="research-hero"'));assert.ok(html.includes('id="research-focus"'));assert.ok(html.includes('id="research-publications"'));assert.ok(html.includes('id="research-process"'));assert.ok(html.includes('/assets/program-research-dashboard.png'));assert.ok(html.includes('/ai-research.css'));});

test('Academy route serves the full designed page',async()=>{const res=await worker.fetch(new Request('https://somdas.test/programs/academy'),env,ctx);assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('id="academy-hero"'));assert.ok(html.includes('id="academy-pathways"'));assert.ok(html.includes('id="academy-courses"'));assert.ok(html.includes('/assets/program-academy-dashboard.png'));assert.ok(html.includes('/academy.css'));});

test('Lab and Solutions have complete, deliberately different page structures',async()=>{const lab=await (await worker.fetch(new Request('https://somdas.test/programs/innovation-lab'),env,ctx)).text();const solutions=await (await worker.fetch(new Request('https://somdas.test/programs/digital-solutions'),env,ctx)).text();assert.ok(lab.includes('SOMDAS Lab'));assert.ok(lab.includes('lab-bench'));assert.ok(lab.includes('/lab.css'));assert.ok(solutions.includes('SOMDAS Solutions'));assert.ok(solutions.includes('solutions-bento'));assert.ok(solutions.includes('/solutions.css'));assert.notEqual(lab,solutions);});

test('Contact page shares navigation and provides a real message form',async()=>{const res=await worker.fetch(new Request('https://somdas.test/contact'),env,ctx);assert.equal(res.status,200);const html=await res.text();assert.ok(html.includes('id="message-form"'));assert.ok(html.includes('href="/contact" aria-current="page"'));assert.ok(html.includes('/contact.js'));});
test('legal and dedicated account pages use the official mark and shared policies',async()=>{for(const path of ['/terms','/privacy','/login','/signup']){const res=await worker.fetch(new Request('https://somdas.test'+path),env,ctx);assert.equal(res.status,200,path);const html=await res.text();assert.ok(html.includes('/assets/somdas-mark.png'));assert.ok(html.includes('href="/privacy"'));assert.ok(html.includes('href="/terms"'));if(path==='/login')assert.ok(html.includes('data-page-auth-form="login"'));if(path==='/signup')assert.ok(html.includes('data-page-auth-form="register"'));}const terms=await (await worker.fetch(new Request('https://somdas.test/terms'),env,ctx)).text();assert.ok(terms.includes('Terms for using SOMDAS.'));assert.ok(terms.includes('data-history-back'));assert.ok(!terms.includes('legal-hero'));assert.ok(!terms.includes('On this page'));const privacy=await (await worker.fetch(new Request('https://somdas.test/privacy'),env,ctx)).text();assert.ok(privacy.includes('How SOMDAS handles your information.'));});
test('anonymous profile visits return to the protected page after sign in',async()=>{const res=await worker.fetch(new Request('https://somdas.test/profile'),env,ctx);assert.equal(res.status,303);assert.equal(res.headers.get('location'),'https://somdas.test/login?returnTo=%2Fprofile');});
test('public member session ignores platform headers and requires a SOMDAS session cookie',async()=>{const anonymous=await (await worker.fetch(new Request('https://somdas.test/api/session'),env,ctx)).json();assert.equal(anonymous.authenticated,false);const platformOnly=await (await worker.fetch(new Request('https://somdas.test/api/session',{headers:{'oai-authenticated-user-email':'member@example.com','oai-authenticated-user-full-name':'Amina%20Ali'}}),env,ctx)).json();assert.deepEqual(platformOnly,{authenticated:false,user:null});});
