import {aboutIcons} from './about-icons';
const {Eye,Target,Database,Search,GraduationCap,Lightbulb,Sprout,MapPin,Users,Network,UserRound,Check}=aboutIcons;
import {renderHome,esc} from './render';
import type {Content} from './content';
const icon=(markup:string)=>markup;
const lines=(s:string)=>esc(s).replace(/\n/g,'<br>');
const paragraphs=(s:string)=>s.split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${lines(p)}</p>`).join('');
const line=`<svg class="about-connector" viewBox="0 0 1600 64" preserveAspectRatio="none" aria-hidden="true"><path class="connector-soft" d="M0 39H310c52 0 43-24 94-24h792c51 0 42 24 94 24h310"/><path class="connector-main" d="M0 50h340c53 0 44-25 96-25h728c52 0 43 25 96 25h340"/><circle cx="340" cy="50" r="4"/><circle cx="800" cy="25" r="4"/><circle cx="1260" cy="50" r="4"/></svg>`;
export function renderAbout(c:Content){
 const a=c.about;let main='';
 if(a.sections.hero)main+=`<section id="about-hero" class="about-hero"><div class="about-wrap"><p class="eyebrow">${esc(a.hero.eyebrow)}</p><h1>${lines(a.hero.title)}</h1><p>${lines(a.hero.body)}</p></div>${line}</section>`;
 if(a.sections.intro)main+=`<section id="about-intro" class="about-intro about-space"><div class="about-wrap about-intro-grid"><div class="about-copy"><p class="eyebrow">${esc(a.intro.eyebrow)}</p><h2>${lines(a.intro.title)}</h2><p class="about-intro-lead">${lines(a.intro.lead)}</p>${paragraphs(a.intro.body)}<div class="about-badges"><span>${icon(MapPin)}Somali-led</span><span>${icon(Users)}Public benefit</span><span>${icon(Network)}Data & AI</span></div></div>${a.intro.image?`<figure class="about-banner"><img src="${esc(a.intro.image)}" alt="SOMDAS roll-up banner" width="768" height="1024" loading="lazy"><figcaption>${icon(MapPin)}${esc(a.intro.caption)}</figcaption></figure>`:''}</div></section>`;
 for(const key of ['vision','mission'] as const){if(!a.sections[key])continue;const s=a[key];main+=`<section id="about-${key}" class="about-statement about-${key} about-space"><div class="about-wrap statement-grid"><div class="statement-icon">${icon(key==='vision'?Eye:Target)}</div><div class="statement-copy"><p class="eyebrow">${esc(s.eyebrow)}</p><h2>${lines(s.title)}</h2><p class="statement-lead">${lines(s.lead)}</p>${paragraphs(s.body)}${key==='mission'?`<ul class="mission-topics">${['Open data','Research','Education','Innovation'].map(t=>`<li>${icon(Check)}${t}</li>`).join('')}</ul>`:''}</div></div></section>`;}
 if(a.sections.difference){const icons=[Database,Search,GraduationCap,Lightbulb,Sprout];main+=`<section id="about-difference" class="about-difference about-space"><div class="about-wrap"><header class="about-centered"><p class="eyebrow">${esc(a.difference.eyebrow)}</p><h2>${lines(a.difference.title)}</h2><p>${lines(a.difference.body)}</p></header><div class="difference-grid">${a.difference.items.map((item,i)=>`<article class="difference-card"><span>${icon(icons[i])}</span><div><h3>${esc(item.title)}</h3><p>${lines(item.body)}</p></div></article>`).join('')}</div><p class="about-principle">Stronger data. Stronger capabilities. Shared progress.</p></div></section>`;}
 const team=a.team.filter(m=>m.visible);
 if(a.sections.team&&team.length)main+=`<section id="about-team" class="about-team about-space"><div class="about-wrap"><header class="about-team-heading"><div><p class="eyebrow">Our Team</p><h2>${lines(a.teamTitle)}</h2></div><p>${lines(a.teamIntro)}</p></header><div class="about-team-grid">${team.map(m=>`<article class="about-person">${m.image?`<img class="person-photo" src="${esc(m.image)}" alt="${esc(m.imageAlt||m.name)}" loading="lazy" width="150" height="150">`:`<div class="person-photo person-avatar" aria-hidden="true">${icon(UserRound)}</div>`}<div class="person-copy"><h3>${esc(m.name)}</h3><p class="person-role">${esc(m.role)}</p><div class="person-bio">${paragraphs(m.bio)}</div>${m.linkedin?`<a class="person-link" href="${esc(m.linkedin)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(m.name)} on LinkedIn"><b aria-hidden="true">in</b><span>LinkedIn</span></a>`:''}</div></article>`).join('')}</div></div></section>`;
 if(a.sections.join)main+=`<section id="about-join" class="about-join about-space"><div class="about-wrap"><div><p class="eyebrow">${esc(a.join.eyebrow)}</p><h2>${lines(a.join.title)}</h2><p>${lines(a.join.body)}</p></div><div class="about-join-actions">${c.sections['get-involved']?'<a class="button" href="/#get-involved">Get involved <span aria-hidden="true">→</span></a>':'<button class="button" data-contact>Get involved <span aria-hidden="true">→</span></button>'}<button class="button button-outline" data-contact>Work with SOMDAS <span aria-hidden="true">→</span></button></div></div>${line}</section>`;
 let html=renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main" class="about-page">${main}</main>`).replace('<title>SOMDAS | Somali Data &amp; AI Society</title>','<title>About SOMDAS | Somali Data &amp; AI Society</title>').replace('</head>','<link rel="stylesheet" href="/about.css"></head>');
 html=html.replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace('class="nav-link" href="/about"','class="nav-link active" href="/about" aria-current="page"');
 // On this route, homepage section links need an explicit homepage path.
 html=html.replace(/href="#(?!main\b)([^\"]+)"/g,'href="/#$1"');
 // Preserve contrast before the dark footer, even when the final section is disabled.
 return html.replace('</body>','<script src="/about.js" defer></script></body>');
}
