import type {Content} from './content';import {renderHome} from './render';import {programNavigator} from './sodi-render';import {sodiIcons as I} from './sodi-icons';
const esc=(s:string)=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!)),lines=(s:string)=>esc(s).replace(/\n/g,'<br>'),paras=(s:string)=>s.split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${lines(x)}</p>`).join(''),head=(b:{eyebrow:string;title:string;body:string})=>`<p class="sodi-eyebrow">${esc(b.eyebrow)}</p><h2>${lines(b.title)}</h2>${paras(b.body)}`;
const art=`<svg class="academy-lines" viewBox="0 0 1600 720" preserveAspectRatio="none" aria-hidden="true"><path d="M0 626h392c73 0 61-86 137-86h104c55 0 49-67 110-67h95"/><path class="dash" d="M0 650h410c72 0 62-82 135-82h126c52 0 44-66 103-66h80"/><g><circle cx="393" cy="626" r="5"/><circle cx="529" cy="540" r="5"/><circle cx="634" cy="540" r="5"/><circle cx="744" cy="473" r="5"/></g></svg>`;
const icons=[I.GraduationCap,I.ChartNoAxesCombined,I.BookOpen,I.Users];
function shell(c:Content,main:string){const html=renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,()=>`<main id="main" class="sodi-page academy-page">${main}</main>`).replace(/<title>[\s\S]*?<\/title>/,'<title>SOMDAS Academy | SOMDAS</title>').replace('</head>','<link rel="stylesheet" href="/sodi.css"><link rel="stylesheet" href="/academy.css"></head>');return html.replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace('<summary class="nav-link">Programs','<summary class="nav-link active">Programs').replace(/href="#(?!main\b)([^\"]+)"/g,'href="/#$1"');}
export function renderAcademy(c:Content){const a=c.academy;let main='';
 if(a.sections.hero)main+=`<section class="academy-hero" id="academy-hero"><div class="academy-hero-copy"><p class="sodi-eyebrow">${esc(a.hero.eyebrow)}</p><h1>${lines(a.hero.title)}</h1><p>${lines(a.hero.body)}</p><a class="button" href="${a.sections.pathways?'#academy-pathways':'/contact'}">Explore learning pathways <span>→</span></a><ul><li>${I.BookOpen}Practical</li><li>${I.Users}Mentored</li><li>${I.GraduationCap}Context-led</li></ul></div>${art}<figure><img src="/assets/program-academy-dashboard.png" width="1536" height="1024" alt="SOMDAS Academy learning portal with courses, progress and an open book" fetchpriority="high"><figcaption>Academy learning experience · illustrative preview</figcaption></figure></section>`;
 if(a.sections.about)main+=`<section class="sodi-space academy-about" id="academy-about"><div class="sodi-wrap academy-split"><header>${head({...a.about,body:''})}</header><div>${paras(a.about.body)}<div class="academy-values"><span>Learn by doing</span><span>Guided feedback</span><span>Useful outcomes</span></div></div></div></section>`;
 if(a.sections.audience)main+=`<section class="sodi-space academy-audience" id="academy-audience"><div class="sodi-wrap"><header class="academy-row"><div>${head({...a.audienceHeading,body:''})}</div><div>${paras(a.audienceHeading.body)}</div></header><div class="academy-audience-grid">${a.audiences.filter(x=>x.visible).map((x,i)=>`<article><span>${icons[i%icons.length]}</span><div><small>0${i+1}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></div></article>`).join('')}</div></div></section>`;
 if(a.sections.pathways)main+=`<section class="sodi-space academy-pathways" id="academy-pathways"><div class="sodi-wrap"><header class="sodi-section-heading">${head(a.pathwaysHeading)}</header><div class="academy-path-grid">${a.pathways.filter(x=>x.visible).map((x,i)=>`<article><span>${icons[(i+1)%icons.length]}</span><small>PATHWAY ${String(i+1).padStart(2,'0')}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')}</div></div></section>`;
 if(a.sections.approach)main+=`<section class="sodi-space academy-approach" id="academy-approach"><div class="sodi-wrap"><header class="academy-row"><div>${head({...a.approach,body:''})}</div><div>${paras(a.approach.body)}</div></header><ol>${[['Understand','Build clear foundations and connect ideas to context.'],['Practice','Work through guided exercises with useful feedback.'],['Build','Apply skills to a project, question or institutional need.'],['Share','Explain the result, reflect and carry the capability forward.']].map(([t,b],i)=>`<li><span>0${i+1}</span><h3>${t}</h3><p>${b}</p></li>`).join('')}</ol></div></section>`;
 if(a.sections.courses){const o=a.offerings.filter(x=>x.visible);main+=`<section class="sodi-space academy-courses" id="academy-courses"><div class="sodi-wrap"><header class="academy-row"><div>${head({...a.courses,body:''})}</div><div>${paras(a.courses.body)}</div></header>${o.length?`<div class="academy-course-grid">${o.map(x=>`<article><div><span>${esc(x.level||'Learning opportunity')}</span><span class="${x.status}">${x.status}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><small>${esc([x.format,x.date].filter(Boolean).join(' · '))}</small>${x.url&&x.status==='open'?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">View registration <span>↗</span></a>`:''}</article>`).join('')}</div>`:`<div class="academy-empty">${I.CalendarDays}<div><strong>No open course is being advertised yet.</strong><p>Confirmed courses and cohorts will be published here through the Academy editor.</p></div></div>`}</div></section>`;}
 if(a.sections.programs){const cc={...c,sodi:{...c.sodi,programs:{title:a.programs.title,body:a.programs.body}}};main+=programNavigator(cc,'academy').replace('id="sodi-programs"','id="academy-programs"');}
 if(a.sections.join)main+=`<section class="sodi-space academy-join" id="academy-join"><div class="sodi-wrap"><div>${head(a.join)}</div><a class="button" href="/contact">Ask about the Academy <span>→</span></a></div></section>`;
 return shell(c,main);
}
