import {z} from 'zod';
const text=(n:number)=>z.string().trim().max(n);
const link=z.string().url().refine(s=>s.startsWith('https://'),'Use an HTTPS URL.').or(z.literal(''));
const imagePath=z.string().regex(/^\/(?:assets\/[a-zA-Z0-9._-]+|media\/[a-f0-9-]+)$/).or(z.literal(''));
const block=z.object({eyebrow:text(80),title:text(180).min(1),body:text(6000)});
export const aiResearchSections={hero:'Hero',about:'About the program',focus:'Research focus areas',publications:'Research & publications',process:'How we research',programs:'Explore SOMDAS programs',join:'Research with us'} as const;
export const aiResearchSchema=z.object({sections:z.object({hero:z.boolean(),about:z.boolean(),focus:z.boolean(),publications:z.boolean(),process:z.boolean(),programs:z.boolean(),join:z.boolean()}),hero:block,about:block,focusHeading:block,focusAreas:z.array(z.object({id:z.string().regex(/^[a-z0-9-]+$/),title:text(120).min(1),body:text(700),visible:z.boolean()})).max(12),publications:block,projects:z.array(z.object({id:z.string().regex(/^[a-z0-9-]+$/),title:text(180).min(1),summary:text(1000),category:text(100),status:z.enum(['ongoing','published']),date:text(40),author:text(180),url:link,image:imagePath,imageAlt:text(250),visible:z.boolean()})).max(100),process:block,programs:block,join:block}).superRefine((s,c)=>{if(new Set(s.focusAreas.map(x=>x.id)).size!==s.focusAreas.length)c.addIssue({code:'custom',message:'Research focus IDs must be unique.'});if(new Set(s.projects.map(x=>x.id)).size!==s.projects.length)c.addIssue({code:'custom',message:'Research item IDs must be unique.'});for(const p of s.projects)if(p.image&&!p.imageAlt)c.addIssue({code:'custom',message:'Every research image needs a description.'});});
export type AiResearchContent=z.infer<typeof aiResearchSchema>;
export const defaultAiResearch:AiResearchContent={sections:{hero:true,about:true,focus:true,publications:true,process:true,programs:true,join:true},hero:{eyebrow:'AI & RESEARCH',title:'Research grounded in\nSomali priorities.',body:'We connect responsible artificial intelligence, careful inquiry and local knowledge to build evidence that can support better decisions.'},about:{eyebrow:'WHY THIS PROGRAM',title:'Questions that matter.\nEvidence that can travel.',body:'Somalia needs research that begins with its own questions and remains useful beyond a single report. AI & Research brings together practitioners, institutions and communities to examine real priorities with appropriate methods.\n\nWe focus on responsible, understandable work—from defining a question and assessing the available data to evaluating results and communicating what they mean. Where possible, outputs are documented and shared for learning and reuse.'},focusHeading:{eyebrow:'RESEARCH FOCUS AREAS',title:'Where inquiry meets\npublic purpose.',body:'Our focus areas reflect important opportunities for evidence, responsible AI and practical collaboration in Somalia.'},focusAreas:[{id:'somali-language-ai',title:'Somali Language AI',body:'Explore language technologies that better understand and serve Somali speakers.',visible:true},{id:'health-wellbeing',title:'Health & Wellbeing',body:'Support stronger evidence for public health, services and community wellbeing.',visible:true},{id:'climate-resilience',title:'Climate, Agriculture & Resilience',body:'Study environmental change, livelihoods and locally relevant adaptation.',visible:true},{id:'education-skills',title:'Education & Skills',body:'Understand learning needs and the pathways that strengthen national capability.',visible:true},{id:'responsible-ai',title:'Responsible & Explainable AI',body:'Develop approaches that are transparent, safe and appropriate for their context.',visible:true}],publications:{eyebrow:'RESEARCH & PUBLICATIONS',title:'Research made clear\nand open where possible.',body:'Projects, working papers and public resources will appear here as they are ready. Each item can include its status, contributors and a link to the full work.'},projects:[],process:{eyebrow:'HOW WE RESEARCH',title:'Responsible from question\nto shared finding.',body:'A clear process helps research remain rigorous, understandable and useful to the people it concerns.'},programs:{eyebrow:'ONE CONNECTED INSTITUTION',title:'Different doors.\nOne shared mission.',body:'Explore how every SOMDAS program contributes to Somalia’s data and AI ecosystem.'},join:{eyebrow:'RESEARCH WITH US',title:'Bring a question.\nBuild the evidence with us.',body:'We welcome conversations with researchers, universities, public institutions, communities and responsible technology partners.'}};
