import type {Content} from './content';
import {renderHome} from './render';
import {programNavigator} from './sodi-render';
import {sodiIcons as I} from './sodi-icons';

const esc=(s:string)=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const lines=(s:string)=>esc(s).replace(/\n/g,'<br>');
const paras=(s:string)=>s.split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${lines(x)}</p>`).join('');
const block=(eyebrow:string,title:string,body:string)=>`<p class="sodi-eyebrow">${esc(eyebrow)}</p><h2>${lines(title)}</h2>${paras(body)}`;
const heroLines=`<svg class="research-hero-lines" viewBox="0 0 1600 760" preserveAspectRatio="none" aria-hidden="true"><path d="M0 674H430c65 0 56-91 126-91h123c54 0 51-76 105-76h75"/><path class="dash" d="M0 698h438c78 0 65-92 133-92h149c43 0 42-55 90-55h63"/><g><circle cx="431" cy="674" r="5"/><circle cx="557" cy="583" r="5"/><circle cx="680" cy="583" r="5"/><circle cx="784" cy="507" r="5"/></g></svg>`;
const focusIcons=[I.Search,I.HeartPulse,I.CloudRain,I.GraduationCap,I.ShieldCheck];

function shell(c:Content,main:string){
 let html=renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,()=>`<main id="main" class="sodi-page research-page">${main}</main>`).replace(/<title>[\s\S]*?<\/title>/,'<title>AI &amp; Research | SOMDAS</title>').replace('</head>','<link rel="stylesheet" href="/sodi.css"><link rel="stylesheet" href="/ai-research.css"></head>');
 html=html.replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace('<summary class="nav-link">Programs','<summary class="nav-link active">Programs').replace(/href="#(?!main\b)([^\"]+)"/g,'href="/#$1"');
 return html;
}

export function renderAiResearch(c:Content){const a=c.aiResearch;let main='';
 if(a.sections.hero)main+=`<section class="research-hero" id="research-hero"><div class="research-hero-copy"><p class="sodi-eyebrow">${esc(a.hero.eyebrow)}</p><h1>${lines(a.hero.title)}</h1><p>${lines(a.hero.body)}</p><a class="button" href="#research-focus">Explore our focus <span aria-hidden="true">→</span></a><ul><li>${I.Search}<span>Applied inquiry</span></li><li>${I.ShieldCheck}<span>Responsible AI</span></li><li>${I.Users}<span>Local knowledge</span></li></ul></div>${heroLines}<figure><div class="research-visual-glow"></div><img src="/assets/program-research-dashboard.png" width="1536" height="1024" alt="Applied AI research dashboard with a neural network, research document and evaluation charts" fetchpriority="high"><figcaption>AI &amp; Research · evidence, evaluation and responsible practice</figcaption></figure></section>`;
 if(a.sections.about)main+=`<section class="sodi-space research-about" id="research-about"><div class="sodi-wrap research-split"><header>${block(a.about.eyebrow,a.about.title,'')}</header><div class="research-rich">${paras(a.about.body)}<div class="research-principles"><span>Somali-led</span><span>Evidence-minded</span><span>Public benefit</span></div></div></div></section>`;
 if(a.sections.focus)main+=`<section class="sodi-space research-focus" id="research-focus"><div class="sodi-wrap"><header class="sodi-section-heading">${block(a.focusHeading.eyebrow,a.focusHeading.title,a.focusHeading.body)}</header><div class="research-focus-grid">${a.focusAreas.filter(x=>x.visible).map((x,i)=>`<article><span class="research-card-no">0${i+1}</span><span class="research-focus-icon">${focusIcons[i%focusIcons.length]}</span><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')}</div></div></section>`;
 if(a.sections.publications){const projects=a.projects.filter(x=>x.visible);main+=`<section class="sodi-space research-publications" id="research-publications"><div class="sodi-wrap"><header class="research-section-row"><div>${block(a.publications.eyebrow,a.publications.title,'')}</div><div>${paras(a.publications.body)}</div></header>${projects.length?`<div class="research-project-grid">${projects.map(p=>`<article class="research-project">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.imageAlt)}" loading="lazy">`:`<div class="research-project-placeholder">${I.FileText}<span>Research</span></div>`}<div class="research-project-copy"><div><span>${esc(p.category||'Research')}</span><span>${p.status==='published'?'Published':'Ongoing'}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p>${p.author||p.date?`<small>${esc([p.author,p.date].filter(Boolean).join(' · '))}</small>`:''}${p.url?`<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Read the full work <span aria-hidden="true">↗</span></a>`:''}</div></article>`).join('')}</div>`:`<div class="research-empty"><span>${I.FileText}</span><div><strong>Research will be added as it is ready.</strong><p>No placeholder publications or invented results—only reviewed work added through the SOMDAS editor.</p></div></div>`}</div></section>`;}
 if(a.sections.process)main+=`<section class="sodi-space research-process" id="research-process"><div class="sodi-wrap"><header class="research-section-row"><div>${block(a.process.eyebrow,a.process.title,'')}</div><div>${paras(a.process.body)}</div></header><ol>${[['Define','Begin with a clear problem, context and people affected.'],['Understand','Assess existing knowledge, data quality, risks and gaps.'],['Develop & evaluate','Choose appropriate methods, test carefully and document limitations.'],['Share & sustain','Communicate useful findings and maintain what deserves a longer life.']].map(([t,b],i)=>`<li><span>0${i+1}</span><div><h3>${t}</h3><p>${b}</p></div></li>`).join('')}</ol></div></section>`;
 if(a.sections.programs){const navContent={...c,sodi:{...c.sodi,programs:{title:a.programs.title,body:a.programs.body}}};main+=programNavigator(navContent,'ai-research').replace('id="sodi-programs"','id="research-programs"');}
 if(a.sections.join)main+=`<section class="sodi-space research-join" id="research-join"><div class="sodi-wrap"><div>${block(a.join.eyebrow,a.join.title,a.join.body)}</div><a class="button" href="/contact">Discuss a research collaboration <span aria-hidden="true">→</span></a></div></section>`;
 if(!a.sections.focus)main=main.replace('href="#research-focus"','href="/contact"');
 return shell(c,main);
}
