import type {Content} from './content';
import {esc,renderHome} from './render';

export type PublicMember={id:string;name:string;email:string;createdAt:string;avatarUrl:string};

function initials(name:string){const words=name.trim().split(/\s+/).filter(Boolean);return esc((words.length>1?words[0][0]+words.at(-1)![0]:name.slice(0,2))||'SM').toUpperCase();}
function joined(value:string){try{return new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});}catch{return '';}}
function dialog(id:string,title:string,body:string,kind=''){return `<dialog class="profile-dialog ${kind}" id="${id}" aria-labelledby="${id}-title"><button class="profile-dialog-close" type="button" data-dialog-close aria-label="Close">×</button><h2 id="${id}-title">${title}</h2>${body}<p class="profile-dialog-status" data-dialog-status role="status" aria-live="polite"></p></dialog>`;}

export function renderProfile(c:Content,member:PublicMember){
 const avatar=member.avatarUrl?`<img src="${esc(member.avatarUrl)}" alt="${esc(member.name)} profile image" data-profile-photo>`:`<span data-profile-fallback>${initials(member.name)}</span>`;
 const main=`<main id="main" class="member-profile" data-member-email="${esc(member.email)}">
  <div class="profile-wrap">
   <header class="profile-heading"><div><p class="eyebrow">${esc(c.auth.profileEyebrow)}</p><h1>${esc(c.auth.profileTitle)}</h1><p>${esc(c.auth.profileIntro)}</p></div><a href="/" class="profile-home">← Back to website</a></header>
   <div class="profile-layout">
    <aside class="profile-summary"><button class="profile-photo" type="button" data-dialog-open="profile-photo-dialog" aria-label="${member.avatarUrl?'Change':'Add'} profile image">${avatar}<span>${member.avatarUrl?'Change photo':'Add photo'}</span></button><h2 data-profile-name>${esc(member.name)}</h2><p>${esc(member.email)}</p><dl><div><dt>Member since</dt><dd>${esc(joined(member.createdAt))}</dd></div><div><dt>Account status</dt><dd><i></i> Active</dd></div></dl></aside>
    <div class="profile-settings">
     <section class="profile-panel"><header><div><p class="eyebrow">PERSONAL INFORMATION</p><h2>Your details</h2></div></header><form data-profile-details><label>Full name<input name="name" autocomplete="name" minlength="2" maxlength="80" value="${esc(member.name)}" required></label><label>Email address<input value="${esc(member.email)}" readonly aria-describedby="email-note"><small id="email-note">Your email identifies this account and cannot currently be changed here.</small></label><div class="profile-form-actions"><button class="button" type="submit">Save changes</button><span data-page-status role="status" aria-live="polite"></span></div></form></section>
     <section class="profile-panel"><header><div><p class="eyebrow">SECURITY</p><h2>Password &amp; access</h2></div></header><div class="profile-action-row"><div><strong>Password</strong><p>Use a unique password of at least 10 characters.</p></div><button class="button button-outline" type="button" data-dialog-open="profile-password-dialog">Change password</button></div><div class="profile-action-row"><div><strong>Sign out</strong><p>End your SOMDAS session on this device.</p></div><button class="profile-text-action" type="button" data-dialog-open="profile-signout-dialog">Sign out</button></div></section>
     <section class="profile-panel profile-danger"><header><div><p class="eyebrow">DANGER ZONE</p><h2>Delete account</h2></div></header><div class="profile-action-row"><div><strong>Permanently delete your account</strong><p>This removes your member profile and active sessions. This action cannot be undone.</p></div><button class="profile-delete-action" type="button" data-dialog-open="profile-delete-dialog">Delete account</button></div></section>
    </div>
   </div>
  </div>
  ${dialog('profile-photo-dialog','Profile photo',`<p>Choose how you want to update your profile photo.</p><div class="profile-current-photo">${avatar}</div><div class="profile-photo-actions"><label class="button profile-source-button">Take a photo<input data-profile-camera type="file" accept="image/*" capture="user"></label><label class="button button-outline profile-source-button">Upload from device<input data-profile-upload type="file" accept="image/jpeg,image/png,image/webp"></label></div>${member.avatarUrl?'<button class="profile-remove-link" type="button" data-dialog-open="profile-remove-dialog">Remove photo</button>':''}`)}
  ${dialog('profile-crop-dialog','Adjust your photo',`<p>Move and zoom the image to fit the circle.</p><div class="profile-crop-stage" data-crop-stage><img data-crop-image alt="Crop preview" hidden><span data-crop-empty>Choose a photo to begin</span><span class="profile-crop-ring" aria-hidden="true"><i class="top"></i><i class="right"></i><i class="bottom"></i><i class="left"></i></span></div><label class="profile-crop-zoom">Zoom<input type="range" data-crop-zoom min="1" max="3" step="0.01" value="1"></label><button type="button" class="profile-dialog-link" data-crop-change>Choose another photo</button><div class="dialog-actions profile-crop-footer"><button class="button button-outline" type="button" data-dialog-close>Cancel</button><button class="button" type="button" data-crop-save disabled>Save crop</button></div>`)}
  ${member.avatarUrl?dialog('profile-remove-dialog','Remove profile photo',`<p>Your current profile photo will be removed from your account.</p><div class="dialog-actions"><button class="button button-outline" type="button" data-dialog-close>Cancel</button><button class="profile-delete-submit" type="button" data-confirm-remove>Remove photo</button></div>`):''}
  ${dialog('profile-password-dialog','Change password',`<p>Confirm your current password, then choose a new one.</p><form data-profile-password><label>Current password<input name="currentPassword" type="password" autocomplete="current-password" maxlength="128" required></label><label>New password<input name="newPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required></label><label>Confirm new password<input name="confirmPassword" type="password" autocomplete="new-password" minlength="10" maxlength="128" required></label><button class="button" type="submit">Update password</button></form><button class="profile-dialog-link" type="button" data-profile-forgot>Forgot your current password?</button>`)}
  ${dialog('profile-signout-dialog','Sign out of SOMDAS?',`<p>You will need your email and password to access your profile again.</p><div class="dialog-actions"><button class="button" type="button" data-confirm-signout>Yes, sign out</button><button class="button button-outline" type="button" data-dialog-close>Cancel</button></div>`)}
  ${dialog('profile-delete-dialog','Permanently delete account?',`<div class="delete-warning"><strong>This cannot be undone.</strong><p>Your member profile, password and active sessions will be permanently removed.</p></div><form data-profile-delete><label>Current password<input name="currentPassword" type="password" autocomplete="current-password" maxlength="128" required></label><label>Type DELETE to confirm<input name="confirmation" autocomplete="off" pattern="DELETE" placeholder="DELETE" required></label><button class="profile-delete-submit" type="submit">Permanently delete account</button></form>`,'profile-delete-dialog')}
 </main>`;
 return renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,()=>main).replace(/<title>[\s\S]*?<\/title>/,'<title>Your profile | SOMDAS</title>').replace('</head>','<link rel="stylesheet" href="/profile.css"></head>').replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace(/href="#(?!main\b)([^"]+)"/g,'href="/#$1"').replace('</body>','<script src="/profile.js" defer></script></body>');
}
