import type {Content} from './content';import type {ProgramPageContent} from './program-pages-content';import {renderHome} from './render';import {programNavigator} from './sodi-render';import {sodiIcons as I} from './sodi-icons';
const esc=(s:string)=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!)),lines=(s:string)=>esc(s).replace(/\n/g,'<br>'),paras=(s:string)=>s.split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${lines(x)}</p>`).join(''),head=(b:{eyebrow:string;title:string;body:string})=>`<p class="sodi-eyebrow">${esc(b.eyebrow)}</p><h2>${lines(b.title)}</h2>${paras(b.body)}`;
const icons=[I.Database,I.FlaskConical,I.Users,I.ChartNoAxesCombined,I.Cable];
function shell(c:Content,title:string,css:string,cls:string,main:string){const html=renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,()=>`<main id="main" class="sodi-page ${cls}">${main}</main>`).replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)} | SOMDAS</title>`).replace('</head>',`<link rel="stylesheet" href="/sodi.css"><link rel="stylesheet" href="/${css}"></head>`);return html.replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace('<summary class="nav-link">Programs','<summary class="nav-link active">Programs').replace(/href="#(?!main\b)([^\"]+)"/g,'href="/#$1"');}
const entryCards=(p:ProgramPageContent,kind:string)=>{const visible=p.entries.filter(x=>x.visible);return visible.length?`<div class="${kind}-entry-grid">${visible.map(x=>`<article><div><span>${esc(x.status)}</span>${I.ArrowUpRight}</div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Explore <span>↗</span></a>`:''}</article>`).join('')}</div>`:`<div class="${kind}-empty">${I.FlaskConical}<div><strong>Nothing is being presented as finished yet.</strong><p>Confirmed work can be added and published from the SOMDAS editor.</p></div></div>`};

export function renderLab(c:Content){const p=c.lab;let main='';
 if(p.sections.hero)main+=`<section class="lab-hero" id="lab-hero"><figure><span class="lab-figure-label">EXPERIMENT / TEST / LEARN</span><img src="/assets/program-lab-dashboard.png" width="1536" height="1024" alt="SOMDAS Lab prototype workspace with connected modules and product wireframes" fetchpriority="high"></figure><div class="lab-hero-copy"><p class="sodi-eyebrow">${esc(p.hero.eyebrow)}</p><h1>${lines(p.hero.title)}</h1><p>${lines(p.hero.body)}</p><a class="button" href="${p.sections.services?'#lab-services':'/contact'}">Enter the Lab <span>→</span></a><div class="lab-formula"><span>QUESTION</span><b>+</b><span>EVIDENCE</span><b>+</b><span>TEST</span></div></div><svg class="lab-grid-line" viewBox="0 0 1600 700" preserveAspectRatio="none" aria-hidden="true"><path d="M0 655h300c70 0 55-68 125-68h180c60 0 52-80 118-80h240"/><circle cx="425" cy="587" r="5"/><circle cx="605" cy="587" r="5"/><circle cx="723" cy="507" r="5"/></svg></section>`;
 if(p.sections.purpose)main+=`<section class="sodi-space lab-purpose" id="lab-purpose"><div class="sodi-wrap lab-purpose-layout"><div><span class="lab-big-number">04</span>${head({...p.purpose,body:''})}</div><div>${paras(p.purpose.body)}</div></div></section>`;
 if(p.sections.services)main+=`<section class="sodi-space lab-services" id="lab-services"><div class="sodi-wrap"><header class="lab-heading-row"><div>${head({...p.servicesHeading,body:''})}</div><div>${paras(p.servicesHeading.body)}</div></header><div class="lab-bench">${p.services.filter(x=>x.visible).map((x,i)=>`<article><span>0${i+1}</span><div class="lab-service-icon">${icons[i%icons.length]}</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')}</div></div></section>`;
 if(p.sections.process)main+=`<section class="sodi-space lab-process" id="lab-process"><div class="sodi-wrap"><header>${head(p.process)}</header><ol>${[['Observe','Define the need, context and assumptions.'],['Prototype','Make the smallest useful version of the idea.'],['Test','Gather evidence from real use and technical evaluation.'],['Improve','Refine, stop or prepare the idea for responsible delivery.']].map(([t,b],i)=>`<li><span>0${i+1}</span><div><h3>${t}</h3><p>${b}</p></div></li>`).join('')}</ol></div></section>`;
 if(p.sections.work)main+=`<section class="sodi-space lab-work" id="lab-work"><div class="sodi-wrap"><header class="lab-heading-row"><div>${head({...p.work,body:''})}</div><div>${paras(p.work.body)}</div></header>${entryCards(p,'lab')}</div></section>`;
 if(p.sections.standards)main+=`<section class="sodi-space lab-standards" id="lab-standards"><div class="sodi-wrap"><div class="lab-standard-mark">LAB<span>04</span></div><div>${head(p.standards)}<div class="lab-standard-tags"><span>Evidence</span><span>Safety</span><span>Accessibility</span><span>Limits documented</span></div></div></div></section>`;
 if(p.sections.programs){const cc={...c,sodi:{...c.sodi,programs:{title:p.programs.title,body:p.programs.body}}};main+=programNavigator(cc,'innovation-lab').replace('id="sodi-programs"','id="lab-programs"');}
 if(p.sections.join)main+=`<section class="sodi-space lab-join" id="lab-join"><div class="sodi-wrap"><div>${head(p.join)}</div><a class="button" href="/contact">Propose a Lab question <span>→</span></a></div></section>`;
 return shell(c,'SOMDAS Lab','lab.css','lab-page',main);}

export function renderSolutions(c:Content){const p=c.solutions;let main='';
 if(p.sections.hero)main+=`<section class="solutions-hero" id="solutions-hero"><div class="solutions-hero-top"><div><p class="sodi-eyebrow">${esc(p.hero.eyebrow)}</p><h1>${lines(p.hero.title)}</h1></div><div><p>${lines(p.hero.body)}</p><a class="button" href="${p.sections.services?'#solutions-services':'/contact'}">Explore capabilities <span>→</span></a></div></div><figure><img src="/assets/program-digital-dashboard.png" width="1536" height="1024" alt="SOMDAS Solutions connected web and mobile applications dashboard" fetchpriority="high"><div class="solutions-floating-card one">${I.ShieldCheck}<span>Responsible delivery</span></div><div class="solutions-floating-card two">${I.Cable}<span>Connected systems</span></div></figure><div class="solutions-signal"><i></i><i></i><i></i><span>NEED → SYSTEM → SERVICE</span></div></section>`;
 if(p.sections.purpose)main+=`<section class="sodi-space solutions-purpose" id="solutions-purpose"><div class="sodi-wrap solutions-purpose-grid"><div>${head({...p.purpose,body:''})}</div><div>${paras(p.purpose.body)}<aside><strong>Technology follows the service.</strong><span>Not the other way around.</span></aside></div></div></section>`;
 if(p.sections.services)main+=`<section class="sodi-space solutions-services" id="solutions-services"><div class="sodi-wrap"><header class="solutions-center">${head(p.servicesHeading)}</header><div class="solutions-bento">${p.services.filter(x=>x.visible).map((x,i)=>`<article class="solution-${i+1}"><span>${icons[i%icons.length]}</span><small>0${i+1}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')}</div></div></section>`;
 if(p.sections.process)main+=`<section class="sodi-space solutions-process" id="solutions-process"><div class="sodi-wrap solutions-process-layout"><header>${head(p.process)}</header><ol>${[['Discover','Clarify users, service, data and constraints.'],['Design','Shape the journey, system and operating model.'],['Deliver','Build, evaluate and release in dependable stages.'],['Maintain','Document ownership, support and future improvement.']].map(([t,b],i)=>`<li><span>0${i+1}</span><div><h3>${t}</h3><p>${b}</p></div></li>`).join('')}</ol></div></section>`;
 if(p.sections.work)main+=`<section class="sodi-space solutions-work" id="solutions-work"><div class="sodi-wrap"><header class="solutions-work-head"><div>${head({...p.work,body:''})}</div><div>${paras(p.work.body)}</div></header>${entryCards(p,'solutions')}</div></section>`;
 if(p.sections.standards)main+=`<section class="sodi-space solutions-standards" id="solutions-standards"><div class="sodi-wrap solutions-standard-grid"><div>${head(p.standards)}</div><ul><li>${I.ShieldCheck}<span><strong>Secure & responsible</strong>Appropriate safeguards and data handling.</span></li><li>${I.Users}<span><strong>Accessible & inclusive</strong>Usable across different people and conditions.</span></li><li>${I.FileText}<span><strong>Documented & maintainable</strong>Built for ownership beyond launch.</span></li></ul></div></section>`;
 if(p.sections.programs){const cc={...c,sodi:{...c.sodi,programs:{title:p.programs.title,body:p.programs.body}}};main+=programNavigator(cc,'digital-solutions').replace('id="sodi-programs"','id="solutions-programs"');}
 if(p.sections.join)main+=`<section class="sodi-space solutions-join" id="solutions-join"><div class="sodi-wrap"><span class="solutions-join-no">05</span><div>${head(p.join)}</div><a class="button" href="/contact">Discuss a digital challenge <span>→</span></a></div></section>`;
 return shell(c,'SOMDAS Solutions','solutions.css','solutions-page',main);}
