import {initialContent,sectionNames,type Content} from './content';
export const pages=[['home','Homepage','/'],['about','About','/about'],['sodi','SODI','/programs/sodi'],['aiResearch','AI & Research','/programs/ai-research'],['academy','SOMDAS Academy','/programs/academy'],['lab','SOMDAS Lab','/programs/innovation-lab'],['solutions','SOMDAS Solutions','/programs/digital-solutions'],['community','Community','/community'],['contact','Contact','/contact'],['account','Login & signup','/login'],['legal','Terms & privacy','/privacy']] as const;
export type Section={key:string,page:string,title:string,paths:string[]};
export const human=(s:string)=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]/g,' ').replace(/^./,x=>x.toUpperCase());
export function catalog(c:Content):Section[]{
 const out:Section[]=[{key:'home:order',page:'home',title:'Homepage section order',paths:['sectionOrder']},...Object.entries(sectionNames).map(([id,title])=>({key:'home:'+id,page:'home',title,paths:['sections.'+id,...(id==='partners'?['partnersTitle','partnersIntro','partners']:id==='community'?['communityTitle','communityIntro','featured']:['home.'+id])]}))];
 const extras:Record<string,Record<string,string[]>>={about:{team:['teamTitle','teamIntro','team']},sodi:{hero:['hero','platformUrl','platformReady'],categories:['categoriesTitle','categoriesIntro','categories']},aiResearch:{focus:['focusHeading','focusAreas'],publications:['publications','projects']},academy:{audience:['audienceHeading','audiences'],pathways:['pathwaysHeading','pathways'],courses:['courses','offerings']},lab:{services:['servicesHeading','services'],work:['work','entries']},solutions:{services:['servicesHeading','services'],work:['work','entries']}};
 for(const page of ['about','sodi','aiResearch','academy','lab','solutions'] as const)for(const id of Object.keys(c[page].sections))out.push({key:page+':'+id,page,title:human(id),paths:[page+'.sections.'+id,...(extras[page]?.[id]??[id]).map(k=>page+'.'+k)]});
 out.push({key:'community:directory',page:'community',title:'Directory introduction & categories',paths:['communityTitle','communityIntro','categories']},{key:'contact:details',page:'contact',title:'Contact details & social links',paths:['contact']});
 out.push({key:'account:copy',page:'account',title:'Login, signup & reset copy',paths:['auth']},{key:'legal:terms',page:'legal',title:'Terms of Use',paths:['legal.terms']},{key:'legal:privacy',page:'legal',title:'Privacy Policy',paths:['legal.privacy']});
 for(const event of c.events)out.push({key:'post:'+event.id,page:'posts',title:event.title,paths:['@'+event.id]});
 return out;
}
function get(c:Content,path:string):unknown {if(path.startsWith('@'))return c.events.find(e=>e.id===path.slice(1));const fallback=path.split('.').reduce((v:any,k)=>v?.[k],initialContent),value=path.split('.').reduce((v:any,k)=>v?.[k],c);return path.startsWith('home.')?{...fallback,...value}:value??fallback;}
export function extract(c:Content,s:Section):Record<string,unknown>{return Object.fromEntries(s.paths.map(p=>[p,structuredClone(get(c,p))]));}
export function merge(c:Content,s:Section,data:Record<string,unknown>):Content {const result=structuredClone(c);for(const path of s.paths){if(!(path in data))throw Error('Missing section field.');if(path.startsWith('@')){if(result.events.some(e=>e.id===path.slice(1)))result.events=result.events.map(e=>e.id===path.slice(1)?data[path] as Content['events'][number]:e);else result.events.push(data[path] as Content['events'][number]);continue;}const keys=path.split('.'),last=keys.pop()!;let target:any=result;for(const key of keys)target=target[key]??(target[key]={});target[last]=structuredClone(data[path]);}return result;}
