import {renderHome,esc} from './render';
import {sodiIcons as I} from './sodi-icons';
import {programRegistry} from './sodi-content';
import type {Content} from './content';
const lines=(s:string)=>esc(s).replace(/\n/g,'<br>');
const paras=(s:string)=>s.split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${lines(p)}</p>`).join('');
const heroLines=`<svg class="sodi-hero-lines" viewBox="0 0 1672 730" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="#59bfff" stroke-width="1.25"><path d="M0 675 H515 C550 675 564 642 606 642 H725 C769 642 781 619 781 579 V461 C781 430 794 410 817 410 H838"/><path opacity=".65" d="M570 675 C594 675 599 658 626 658 H735 C777 658 788 636 788 603 V548 C788 520 807 505 838 505"/><path stroke-dasharray="2 3" d="M0 696 H533 C577 696 589 642 620 642 H726 C772 642 788 623 788 581 V548 C788 521 805 505 838 505"/></g><g fill="#07163b" stroke="#55b9ff"><circle cx="533" cy="696" r="2.5"/><circle cx="788" cy="619" r="2"/></g><g fill="#52abff"><circle cx="836" cy="410" r="5"/><circle cx="836" cy="505" r="5"/></g></svg>`;
const programLines=`<svg class="program-section-lines" viewBox="0 0 1672 165" preserveAspectRatio="none" aria-hidden="true"><g fill="none" stroke="#0874ff" stroke-width="1.2"><path stroke-dasharray="2 3" d="M0 115 H401 C465 115 449 59 516 59 H693 C732 59 721 28 754 27 C788 27 795 3 795 -40"/><path d="M0 134 H434 C479 134 480 86 532 86 H697 C740 86 720 66 756 66 C799 66 801 26 801 -40"/><path d="M0 153 H447 C489 153 489 119 543 119 H708 C751 119 715 125 795 125 H1672" opacity=".6"/></g><g fill="var(--sodi-surface,#fff)" stroke="#0874ff"><circle cx="401" cy="115" r="4"/><circle cx="629" cy="86" r="3.5"/><circle cx="693" cy="59" r="3"/><circle cx="795" cy="125" r="4"/><circle cx="1424" cy="125" r="4"/></g></svg>`;
const icons=[I.Database,I.Search,I.BookOpen,I.FlaskConical,I.Users];
const programArtwork:Record<string,{src:string;alt:string}>={
 'sodi':{src:'/assets/program-sodi-dashboard.png',alt:'SODI data catalog illustration with search, dataset rows and a donut chart'},
 'ai-research':{src:'/assets/program-research-dashboard.png',alt:'Applied AI research illustration with a neural network, research document and evaluation charts'},
 'academy':{src:'/assets/program-academy-dashboard.png',alt:'SOMDAS Academy learning portal illustration with courses, progress and an open book'},
 'innovation-lab':{src:'/assets/program-lab-dashboard.png',alt:'SOMDAS Lab prototype workspace illustration with connected modules and product wireframes'},
 'digital-solutions':{src:'/assets/program-digital-dashboard.png',alt:'SOMDAS Solutions illustration of connected web and mobile applications'}
};
export function programNavigator(c:Content,current='sodi'){
 const active=programRegistry.find(p=>p.id===current)||programRegistry[0];
 return `<section class="program-navigation sodi-space" id="sodi-programs"><div class="program-nav-layout"><div class="program-nav-left"><h2>${lines(c.sodi.programs.title)}</h2><p class="program-nav-description">${lines(c.sodi.programs.body)}</p><div class="program-feature ${current==='sodi'?'is-sodi':''}"><img class="program-feature-art" src="${programArtwork[active.id].src}" alt="${programArtwork[active.id].alt}" width="1536" height="1024" loading="lazy"><div class="program-feature-copy"><span class="program-id">${active.number}</span><h3>${esc(active.name)}</h3><p>${esc(active.description)}</p><span class="program-here" aria-current="page">You’re here <span aria-hidden="true">→</span></span></div></div></div><div class="program-nav-rows">${programRegistry.filter(p=>p.id!==current).map(p=>`<a href="${p.path}" class="program-nav-row"><span class="program-row-number">${p.number}</span><span class="program-row-icon">${icons[programRegistry.indexOf(p)]}</span><span class="program-row-copy"><strong>${esc(p.name)}</strong><span>${esc(p.description)}</span></span><span class="program-row-explore">Explore <span aria-hidden="true">⟶</span></span></a>`).join('')}</div></div>${programLines}</section>`;
}
function pageShell(c:Content,title:string,main:string){
 let html=renderHome(c).replace(/<main id="main">[\s\S]*?<\/main>/,()=>`<main id="main" class="sodi-page">${main}</main>`).replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)} | SOMDAS</title>`).replace('</head>','<link rel="stylesheet" href="/sodi.css"></head>');
 html=html.replace('class="nav-link active" href="./" aria-current="page"','class="nav-link" href="/"').replace('<summary class="nav-link">Programs','<summary class="nav-link active">Programs');
 html=html.replace(/href="#(?!main\b)([^\"]+)"/g,'href="/#$1"');
 // SODI section links belong to this page, unlike shared footer links.
 html=html.replaceAll('href="/#sodi-about"','href="#sodi-about"').replaceAll('href="/#sodi-categories"','href="#sodi-categories"').replaceAll('href="/#sodi-join"','href="#sodi-join"');
 return html;
}
export function renderSodi(c:Content){const s=c.sodi;let main='';
 const visit=(label='Visit SODI Platform')=>s.platformReady&&s.platformUrl?`<a class="button" href="${esc(s.platformUrl)}" target="_blank" rel="noopener noreferrer">${label} <span aria-hidden="true">→</span></a>`:`<a class="button" href="#sodi-about">Discover SODI <span aria-hidden="true">→</span></a>`;
 if(s.sections.hero)main+=`<section class="sodi-intro-hero" id="sodi-hero"><div class="sodi-hero-copy"><p class="sodi-eyebrow">SODI</p><h1>${lines(s.hero.title)}</h1><p class="sodi-hero-description">${lines(s.hero.body)}</p>${visit()}<ul class="sodi-hero-benefits"><li><span>${I.FileText}</span>Clear metadata</li><li><span>${I.Download}</span>Reusable formats</li><li><span>${I.LockOpen}</span>Free access</li></ul></div>${heroLines}<figure class="sodi-hero-preview"><img src="/assets/sodi-hero-catalog.png" alt="A search bar and example data catalog entries for climate, population and education indicators." width="832" height="549" fetchpriority="high"></figure></section>`;
 if(s.sections.about)main+=`<section class="sodi-space sodi-about" id="sodi-about"><div class="sodi-wrap sodi-two-column"><div><p class="sodi-eyebrow">Somalia Open Data Initiative</p><h2>${lines(s.about.title)}</h2><div class="sodi-tags"><span>Nonprofit initiative</span><span>Free access</span><span>Somalia & beyond</span></div></div><div class="sodi-body">${paras(s.about.body)}</div></div></section>`;
 const categoryIcons:Record<string,string>={health:I.HeartPulse,education:I.GraduationCap,agriculture:I.Sprout,climate:I.CloudRain,economy:I.ChartNoAxesCombined,population:I.Users,governance:I.Landmark,infrastructure:I.Cable};
 if(s.sections.categories)main+=`<section class="sodi-space sodi-categories" id="sodi-categories"><div class="sodi-wrap"><header class="sodi-section-heading"><p class="sodi-eyebrow">Explore data categories</p><h2>${lines(s.categoriesTitle)}</h2><p>${lines(s.categoriesIntro)}</p></header><div class="sodi-category-grid">${s.categories.filter(x=>x.visible).map((cat,i)=>{const linked=s.platformReady&&cat.url;return `<${linked?'a':'article'} ${linked?`href="${esc(cat.url)}" target="_blank" rel="noopener noreferrer"`:''} class="sodi-category-card"><span class="sodi-category-icon">${categoryIcons[cat.id]||I.Database}</span><h3>${esc(cat.title)}</h3><p>${esc(cat.body)}</p><span class="sodi-category-action">${linked?'Explore datasets <span aria-hidden="true">→</span>':'Planned category'}</span></${linked?'a':'article'}>`;}).join('')}</div>${s.platformReady?`<div class="sodi-category-footer">${visit('View all datasets')}</div>`:''}</div></section>`;
 if(s.sections.features)main+=`<section class="sodi-space sodi-features" id="sodi-features"><div class="sodi-wrap sodi-two-column"><header><p class="sodi-eyebrow">What you’ll find on SODI</p><h2>${lines(s.features.title)}</h2><p>${lines(s.features.body)}</p></header><div class="sodi-feature-list">${[[I.FileText,'Clear descriptions & metadata','Understand what a dataset contains, how it was collected and what its fields mean.'],[I.MapPin,'Sources & coverage','Check the publisher, geographic scope and time period before using the data.'],[I.Download,'Reusable files','Find the available formats and choose the file that fits your workflow.'],[I.ShieldCheck,'Licenses & attribution','See the reuse terms and how to credit the original source.'],[I.RefreshCw,'Updates & versions','Know when a dataset was updated and what changed.']].map(([icon,title,body])=>`<article>${icon}<div><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div></div></section>`;
 if(s.sections.process)main+=`<section class="sodi-space sodi-process" id="sodi-process"><div class="sodi-wrap"><header class="sodi-section-heading"><p class="sodi-eyebrow">How we prepare data</p><h2>${lines(s.process.title)}</h2><p>${lines(s.process.body)}</p></header><ol class="sodi-process-steps">${[['Collect','Identify useful sources and datasets.'],['Review','Check quality, permissions and sensitive information.'],['Document','Describe the source, fields, coverage and license.'],['Publish','Make approved datasets discoverable and accessible.'],['Maintain','Record updates and preserve version history.']].map(([title,body],i)=>`<li><span>0${i+1}</span><h3>${title}</h3><p>${body}</p></li>`).join('')}</ol></div></section>`;
 if(s.sections.programs)main+=programNavigator(c);
 if(s.sections.join)main+=`<section class="sodi-space sodi-join" id="sodi-join"><div class="sodi-wrap sodi-two-column"><div><p class="sodi-eyebrow">Explore or contribute</p><h2>${lines(s.join.title)}</h2><p>${lines(s.join.body)}</p></div><div class="sodi-contribute"><h3>Contribute a dataset</h3><p>Prepare a source link, a short description, the geographic and time coverage, and information about permission to share it.</p><button class="button" data-contact>Prepare a contribution <span aria-hidden="true">→</span></button>${s.platformReady?visit():`<p class="sodi-platform-status">The SODI platform is in development.</p>`}</div></div></section>`;
 // An absent section must not leave its internal CTA pointing to a missing anchor.
 if(!s.sections.about)main=main.replaceAll('<a class="button" href="#sodi-about">Discover SODI <span aria-hidden="true">→</span></a>','<button class="button" data-contact>Ask about SODI <span aria-hidden="true">→</span></button>');
 return pageShell(c,'SODI | Somalia Open Data Initiative',main);
}
export function renderProgramIntro(c:Content,id:string){const p=programRegistry.find(p=>p.id===id);if(!p)return null;
 const intros:Record<string,string>={'ai-research':'SOMDAS brings research questions back to Somali priorities. This program focuses on responsible inquiry, applied AI and evidence that can support useful decisions.','academy':'SOMDAS Academy focuses on practical data and AI learning, mentorship and knowledge sharing. Its purpose is to help people build capabilities they can apply to real questions.','innovation-lab':'SOMDAS Lab connects research and ideas with practical experimentation. It focuses on understanding real needs, developing prototypes and learning through testing.','digital-solutions':'SOMDAS Solutions focuses on useful, inclusive technology for institutions and communities. It connects technical development with the people and services it is intended to support.'};
 return pageShell(c,p.name,`<section class="sodi-space program-overview"><div class="sodi-wrap"><p class="sodi-eyebrow">SOMDAS program ${p.number}</p><h1>${esc(p.name)}</h1><p>${esc(intros[id]||p.description)}</p><button class="button" data-contact>Discuss this program <span aria-hidden="true">→</span></button></div></section>${programNavigator(c,id)}`);
}
