import {z} from 'zod';
const text=(n:number)=>z.string().trim().max(n);
const link=z.string().url().refine(s=>s.startsWith('https://'),'Use an HTTPS URL.').or(z.literal(''));
const block=z.object({title:text(180).min(1),body:text(6000)});
export const sodiSections={hero:'SODI hero',about:'About SODI',categories:'Data categories',features:'What you will find',process:'How we prepare data',programs:'Explore SOMDAS programs',join:'Explore or contribute'} as const;
export const sodiSchema=z.object({sections:z.object({hero:z.boolean(),about:z.boolean(),categories:z.boolean(),features:z.boolean(),process:z.boolean(),programs:z.boolean(),join:z.boolean()}),
 platformUrl:link,platformReady:z.boolean(),hero:block,about:block,categoriesTitle:text(180).min(1),categoriesIntro:text(700),
 categories:z.array(z.object({id:z.string().regex(/^[a-z0-9-]+$/),title:text(100).min(1),body:text(500),url:link,visible:z.boolean()})).max(24),
 features:block,process:block,programs:block,join:block
}).superRefine((s,c)=>{if(s.platformReady&&!s.platformUrl)c.addIssue({code:'custom',message:'Add the live platform URL before marking SODI as available.'});if(new Set(s.categories.map(x=>x.id)).size!==s.categories.length)c.addIssue({code:'custom',message:'Category IDs must be unique.'});});
export type SodiContent=z.infer<typeof sodiSchema>;
export const defaultSodi:SodiContent={
 sections:{hero:true,about:true,categories:true,features:true,process:true,programs:true,join:true},platformUrl:'',platformReady:false,
 hero:{title:'Somalia’s data should\nbe easier to find—and\neasier to trust.',body:'SODI is a nonprofit platform being developed for free access to well-described datasets from Somalia and beyond, for research, learning and informed decisions.'},
 about:{title:'Open knowledge.\nShared possibilities.',body:'The Somalia Open Data Initiative (SODI) is building a searchable home for data that supports research, learning and informed decisions.\n\nSomalia is our starting point. We also aim to connect people with useful datasets from other places, giving local questions a wider context.\n\nAccess will be free. Each dataset will include its source and reuse license so you can understand where it comes from and how it may be used.'},
 categoriesTitle:'Find data around\nthe questions that matter.',categoriesIntro:'Explore the subject areas we are building towards. Published datasets and category links will become available on the SODI platform.',
 categories:[{id:'health',title:'Health',body:'Public health, health services and wellbeing.',url:'',visible:true},{id:'education',title:'Education',body:'Schools, access to education and learning indicators.',url:'',visible:true},{id:'agriculture',title:'Agriculture & Food',body:'Crops, farming, livelihoods and food security.',url:'',visible:true},{id:'climate',title:'Climate & Environment',body:'Rainfall, temperature, drought and environmental change.',url:'',visible:true},{id:'economy',title:'Economy & Business',body:'Prices, trade, businesses and economic indicators.',url:'',visible:true},{id:'population',title:'Population & Society',body:'Population, demographics and social conditions.',url:'',visible:true},{id:'governance',title:'Governance & Public Services',body:'Public institutions, governance and service delivery.',url:'',visible:true},{id:'infrastructure',title:'Infrastructure & Connectivity',body:'Transport, energy, infrastructure and telecommunications.',url:'',visible:true}],
 features:{title:'More than a file.\nThe context to use it.',body:'The platform is being designed to help you discover a dataset, understand its context and decide whether it fits your work.'},
 process:{title:'From source to shared data.',body:'Useful open data needs care at every stage. This is the workflow we are building around each dataset.'},
 programs:{title:'Different doors.\nOne shared mission.',body:'Each program tackles a different part of Somalia’s data and AI ecosystem.'},
 join:{title:'Explore the data.\nOr help make it available.',body:'Have a dataset or know a useful source? Help build a stronger foundation for research, learning and public knowledge.'}
};
export const programRegistry=[{id:'sodi',number:'01',name:'SODI',description:'Open, well-described Somalia-related data.',path:'/programs/sodi',icon:'Database'},{id:'ai-research',number:'02',name:'AI & Research',description:'Responsible inquiry around Somali priorities.',path:'/programs/ai-research',icon:'Search'},{id:'academy',number:'03',name:'SOMDAS Academy',description:'Practical learning, mentorship and capacity building.',path:'/programs/academy',icon:'GraduationCap'},{id:'innovation-lab',number:'04',name:'SOMDAS Lab',description:'Prototypes shaped by evidence and real needs.',path:'/programs/innovation-lab',icon:'Lightbulb'},{id:'digital-solutions',number:'05',name:'SOMDAS Solutions',description:'Inclusive tools for institutions and communities.',path:'/programs/digital-solutions',icon:'Users'}] as const;
